### ISSUE TITLE
Civetweb 1.10: Changed behavior regarding existing index files and "301 Moved Permanently"

### ISSUE THREAD

**Issue by nfrmtkr** [civetweb/civetweb#557] opened 2017-11-24 13:49 UTC
We moved from 1.9.1 to 1.10 and detected following incompatible behavior.

Imagine following directory structure:

./webroot
./webroot/app1
./webroot/app1/index.html

The document_root is set to ./webroot.

and we open http://localhost/app1

In 1.91. we get:

HTTP/1.1 301 Moved Permanently
Location: /app1/
Date: Fri, 24 Nov 2017 09:35:45 GMT
Content-Length: 0

The browser implicitely executes another GET request on http://localhost:5000/xwa/ (slash append) and loading index file as well as subsequent files for our app (css json etc,) works fine.

But in 1.10 we get the index.html file returned directly and loading subsequent files lead to 404 because the "Location" hasn't changed.

I am not sure if the new or old behavior is correct. If the new behavior is a bug, how we can fix it. If the old behavior was a bug, how can I achieve to change the "Location".

**Comment by bel2125** [comment] 2017-11-25 10:44
Maybe this is due to an enhancement in 1.10: 
index script files are allowed to have script handled resources
so, /some/path/to/something may be handled by /some/path/index.cgi with script argument to/something, or by /some/index.cgi with script argument path/to/something, or by /some/path/to/something/index.cgi or /some/path/to/something/index.html
This allows to have dynamic URLs without .cgi, .php, .lua, ... in the path.

However, this enhancement seems to have some unexpected side effects.

Did you configure `allow_index_script_resource`?

**Comment by bel2125** [comment] 2017-11-25 14:59
I just tested in the current 1.11 head version: 
If a directory tree looks like this:
```
--- index.html
 |--- x
   |---  index.cgi
 |--- y
```
Then /y will redirect to /y/ .. showing an empty directory listing
While /x and /x/ will both execute index.cgi
And /z and /z/ will both show a 404 Not Found

index.html is not shown for /y, /y/, /x, /x/, /z or /z/

Could you post a directory tree used to reproduce this issue?

**Comment by nfrmtkr** [comment] 2017-11-27 10:34
The behavior you describe is the same I've debugged in my environment.
The option "allow_index_script_resource" is not used in our code.

Our directory tree looks as follows:

lib
  | --- ...
xwa
 | --- resources 
     | --- ...
 | --- app-all.js
 | --- app.css
 | --- cfg.js
 | --- index.html
favicon.ico

If I rename index.html to xindex.html, then the redirect takes place.
In index.html we have to references to java script no longer working:

  
  <script type="text/javascript" src="cfg.js"></script>
  
  <script type="text/javascript" src="app-all.js"></script>

because it asumes that location is redirected to /xwa.

**Comment by nfrmtkr** [comment] 2017-11-27 10:56
I've tested this with Apache: Accessing the xwa directory without leading slash leads to "301 Moved Permanently" like it was with civetweb 1.9.

Test using curl:
curl -v http://localhost:82/xwa
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 82 (#0)
> GET /xwa HTTP/1.1
> Host: localhost:82
> User-Agent: curl/7.56.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Date: Mon, 27 Nov 2017 10:50:57 GMT
< Server: Apache/2.4.29 (Win32) OpenSSL/1.0.2l PHP/7.1.11
< Location: http://localhost:82/xwa/
< Content-Length: 332
< Content-Type: text/html; charset=iso-8859-1
<
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="http://localhost:82/xwa/">here</a>.</p>
<hr>
<address>Apache/2.4.29 (Win32) OpenSSL/1.0.2l PHP/7.1.11 Server at localhost Port 82</address>
</body></html>
* Connection #0 to host localhost left intact

**Comment by bel2125** [comment] 2017-11-27 20:49
> Our directory tree looks as follows:
```
lib
  | --- ...
xwa
 | --- resources 
     | --- ...
 | --- app-all.js
 | --- app.css
 | --- cfg.js
 | --- index.html
favicon.ico
```
(I added the `\`` before and after, so it's formatted more readable)

So, the structure of your `xwa` directory is basically like this (https://github.com/civetweb/civetweb/tree/master/test/htmldir) ?
I can reproduce it makes a difference if you open "http://localhost:8080/htmldir" or "http://localhost:8080/htmldir/" - the html content is the same, just js and css do not work. That's definitely an undesired side effect in 1.10.
I will have a look how to fix this and still support script resources.

**Comment by nfrmtkr** [comment] 2017-11-27 20:55
Yes. THe test/htmldir is hits the issue I reported.

**Comment by bel2125** [comment] 2017-11-27 22:01
As a quick fix, you could copy section 12 of `handle_request` before section 5.2.2,

```C
...
	} else {
	no_callback_resource:


        /* 12. Directory uris should end with a slash */
        if (file.stat.is_directory && (uri_len > 0)
            && (ri->local_uri[uri_len - 1] != '/')) {
            gmt_time_string(date, sizeof(date), &curtime);
            mg_printf(conn,
                      "HTTP/1.1 301 Moved Permanently\r\n"
                      "Location: %s/\r\n"
                      "Date: %s\r\n"
                      /* "Cache-Control: private\r\n" (= default) */
                      "Content-Length: 0\r\n"
                      "Connection: %s\r\n",
                      ri->request_uri,
                      date,
                      suggest_connection_header(conn));
            send_additional_header(conn);
            mg_printf(conn, "\r\n");
            return;
        }

		/* 5.2.2. No callback is responsible for this request. The URI
		 * addresses a file based resource (static content or Lua/cgi
		 * scripts in the file system). */
		is_callback_resource = 0;
		interpret_uri(conn,
		              path,
		              sizeof(path),
		              &file.stat,
		              &is_found,
		              &is_script_resource,
		              &is_websocket_request,
		              &is_put_or_delete_request);
	}
```

A real fix without side effect on new features is much more complicated ... I will have a look.

**Comment by nfrmtkr** [comment] 2017-12-01 12:02
I've tested the suggested fix. It doesn't change the behavior in civetweb 1.10 release. Are you sure it works with your trunk version?
Knowing the area you try to fix it, I started debugging this use case. I have following fix:

Inside interpret_uri() change the if clause at point 8.3 as follows:

    int uri_len = (int)strlen(uri);
    if (filestat->is_directory && (uri_len > 0)
        && (uri[uri_len - 1] == '/')) {

The code change you've suggested is not necessary with my fix. The code can be placed bacl to point 12!

**Comment by bel2125** [comment] 2017-12-02 22:21
> Are you sure it works with your trunk version?

Before posting the fix, I tested it with the head version and the htmldir test case on Linux.
I did not test the 1.10 release, and I did not test Windows.

I added your fix and will check for possible side effects in the next days.

**Comment by bel2125** [comment] 2018-03-29 21:31
Fixed quite some time ago (and forgotten to close this issue).

**Closed by bel2125** 2018-03-29 21:31 UTC
