### ISSUE TITLE
LUA connect() function failing

### ISSUE THREAD

**Issue by seansbox** [civetweb/civetweb#745] opened 2019-03-22 23:34 UTC
Created a basic testconnect.lua and served using civetweb:

    mg.write("HTTP/1.0 200 OK\r\nContent-Type: text/html\r\n\r\n")

    local host = 'www.example.com'
    local ok, sock = pcall(connect, host, 80, 0)
    if ok then
      sock:send('GET / HTTP/1.0\r\n' ..
                'Host: ' .. host .. '\r\n\r\n')
      local reply = sock:recv()
      sock:close()
      mg.write("START")
      mg.write(reply)
      mg.write("END")
    else
      mg.write("ERROR")
    end

When I use civetweb version 1.11 to serve the file:

    git checkout v1.11
    make build WITH_LUA=1 WITH_WEBSOCKET=1 WITH_ZLIB=1

I get this error on the console and civetweb crashes:

    Loading config file ./civetweb.conf
    CivetWeb V1.11 started on port(s) 8081, 8082s with web root [/Users/sean/Documents/Development/web-civet]
    Segmentation fault: 11

When I use civetweb version 1.10 to serve the file:

    git checkout v1.10
    make build WITH_LUA=1 WITH_WEBSOCKET=1 WITH_ZLIB=1

Civetweb does not crash but the web browser prints "STARTEND" and the "reply" variable is nil.

Here is my civetweb.conf:

    listening_ports 8081, 8082s
    document_root .
    ssl_certificate server.pem

**Comment by xtne6f** [comment] 2019-03-23 03:08
The segmentation fault would be caused by a bug of v1.11 ( I have fixed it by 5d6dea363daff51dba9d005e1e44eb35a627d8e6 ).
I think the nil result of the "reply" is the specification of `connect()`. Although `connect()` create non-blocking (asynchronous) sockets, `sock:recv()` is the synchronous recv() method.

**Comment by seansbox** [comment] 2019-03-23 12:14
Thanks for the response! I will check 5d6dea3. I bet that’s it. As for the recv method, is there a way to use it asyncronously or wait for data from within LUA? Forgive me if this is documented somewhere. I thought I looked through all of the docs.

**Comment by xtne6f** [comment] 2019-03-26 11:30
This issue has been fixed at #748 (`connect()` has changed to synchronous one), so I recommend you cherry-pick 5d6dea363daff51dba9d005e1e44eb35a627d8e6 and bc3d4af22e4c1d1be1d53dcea681f77643c9d043, or simply use [master](https://github.com/civetweb/civetweb/commits/master).
I highly recommend the master unless there is some special reason, because CivetWeb does not backport bugfixes into the release branches. (This is my opinion, the project owner might have a different opinion.)

**Comment by bel2125** [comment] 2021-04-07 05:32
Closing this issue, since it has already been fixed ~2 years ago.

**Closed by bel2125** 2021-04-07 05:32 UTC
