### ISSUE TITLE
access log & num_bytes_sent

### ISSUE THREAD

**Issue by theanalyst** [civetweb/civetweb#459] opened 2017-05-16 17:09 UTC
I haven't looked in great detail, so not sure if this is a bug.

if we only call `mg_write` from my application, then `log_access` always seems to always log 0 bytes sent to client even though `mg_write` would have a +ve return value, is there somewhere else that this is supposed to get set?

**Comment by bel2125** [comment] 2017-05-18 19:17
Since it does not include callback I think it's just not fully implemented, and nobody complained up to now.
After a brief look at the code, it seems easier to implement it for everything, as compared to the current implementation that excludes callbacks.

I think I will change this in the next days.

**Comment by bel2125** [comment] 2017-05-28 20:49
`num_bytes_sent` is now increased directly in `mg_write`.
This works for everything except chunked transfer encoding ... or ... it also works for chunked transfer encoding but counts the bytes after instead of before encoding. The problem is - while it would be possible to only count the bytes before chunked encoding, if civetweb.c sends the response - I think it is not possible (reasonable) if some callback uses mg_write to send chunked encoding.

**Comment by bel2125** [comment] 2017-07-05 19:47
I think there is no reasonable way to have chunked encoding count only the payload, without counting the chunk encoding frame overhead. Even if it would be possible, I'm not sure if it should be done - I think it's just a matter of specification.

Anyway, I would tend to keep it like the first fix from May, and add a comment regarding chunked encoding somewhere in the documentation.

**Comment by bel2125** [comment] 2017-08-20 21:12
Fixed some weeks ago, no reports of persisting problems.
Closing this issue.

**Closed by bel2125** 2017-08-20 21:12 UTC
Labels: Status: done - waiting for submitter to confirm
