### ISSUE TITLE
NULL deref in set_ssl_option()

### ISSUE THREAD

**Issue by snej** [civetweb/civetweb#444] opened 2017-04-17 01:27 UTC
The Clang static analyzer reports a "Dereference of null pointer" in function set_ssl_option(). Specifically, if `ctx->config[SSL_CERTIFICATE] == NULL`, and `ctx->config[SSL_CERTIFICATE_CHAIN] == NULL`, but `ctx->callbacks.init_ssl != NULL`, it will crash.

**Comment by bel2125** [comment] 2017-04-17 19:45
If `ctx->config[SSL_CERTIFICATE]` is null, and a HTTPS `listening_port` (e.g. "443s") is configured, the code will not reach this point but refuse to start with a "*Cannot add SSL socket (entry %i). Is -ssl_certificate option set?*" error message. But this cannot be seen by just looking at this function.
In addition, all uses of `pem` after the assignment `pem = ctx->config[SSL_CERTIFICATE]` are checked as well.

What version of civetweb are you using, and what line do you get this warning?
Did you manage to get this crash in reality, or is it just a theoretical result from static source code analysis (essentially a false positive)?

I actually did a Coverity scan every now and than, and eliminated all "priority high" defects (including all "dereferencing NULL") errors reported by Coverity already last year. Except of the high priority defects in third party components (such as Lua, sqlite3, Duktape, ...). I did not repeat the Coverity check for some months, since they introduced a bug that "should be solved in February 2017" (the filter for third party components stopped working, so all third party components got included). Maybe they fixed it now ...

**Comment by bel2125** [comment] 2017-04-17 21:24
It seems they did not fix the bug. Coverity is still counting warnings in third party components, but not showing them in the list of active warnings. Probably I have to write yet another mail to their support, or try to find a workaround.

Anyway, since this could take a while, could you provide detailed logs of where clang believes to see an error, and version you used to run the code analysis? I can try to add an additional checks in the code, but without the full log, I cannot be sure clang will like it more afterwards.
Or is there an easy way to run this test on my own? I never used clang static code analysis, since there is coverity (which worked quite well for a long time, until the filter somehow broke).

**Comment by bel2125** [comment] 2017-04-17 21:46
I could only imagine, this might help:
432b51f5dc6e5929fb980e598b1c73af11fe8380

**Comment by bel2125** [comment] 2017-04-20 19:50
In the meantime I found out how to get Coverity running again (by an ugly hack that just removes the `third_party` folder from the archive used for scanning), and I found out the clang static analyser can be used by just using `scan-build make` in Linux.

Clang just gives me some warnings in `mg_get_system_info_impl` (all of them false positives):
```
src/civetweb.c:15486:4: warning: Null pointer passed as an argument to a 'nonnull' parameter
                        strcat(buffer, block);
                        ^~~~~~~~~~~~~~~~~~~~~
src/civetweb.c:15511:4: warning: Null pointer passed as an argument to a 'nonnull' parameter
                        strcat(buffer, block);
                        ^~~~~~~~~~~~~~~~~~~~~
src/civetweb.c:15551:4: warning: Null pointer passed as an argument to a 'nonnull' parameter
                        strcat(buffer, block);
                        ^~~~~~~~~~~~~~~~~~~~~
src/civetweb.c:15623:4: warning: Null pointer passed as an argument to a 'nonnull' parameter
                        strcat(buffer, block);
                        ^~~~~~~~~~~~~~~~~~~~~
src/civetweb.c:15709:4: warning: Null pointer passed as an argument to a 'nonnull' parameter
                        strcat(buffer, block);
                        ^~~~~~~~~~~~~~~~~~~~~
5 warnings generated.
```
And Coverity reports two issues:
- (Medium) Waiting while holding a lock (when websocket writes are used for throttled connections)
- (Low) Time of check time of use (in `delete_file` when using `access` to return 403 instead of 423 for write protected files

Maybe the patch above already fixed the warning.
If not, I need some more information.

**Comment by snej** [comment] 2017-04-24 17:03
I've only seen this through running the static analyzer. I run it via Xcode, so I'm not sure what the command-line invocation would be.

**Comment by bel2125** [comment] 2017-04-24 18:32
XCode is something only running on Mac (as to my knowledge), and I don't have one, so I cannot reproduce it on my own.

Maybe it is already fixed in the current version? 
Could you retry with the current head version from GitHub?
If the error still exists, could you post the detailed output from the static analyzer?
I wonder if clang finds more than Coverity?

**Comment by snej** [comment] 2017-04-24 19:18
The Clang static analyzer is cross-platform. Apparently it's a separate binary from Clang itself; you can read docs [here](http://clang-analyzer.llvm.org). Its output isn't easily cut-and-pasteable because it shows the control flow as visual annotations to the source code. In Xcode it appears directly in the editor, on other platforms the analyzer emits HTML files you view in a browser. I've found it very useful, although like any other tool it does find some false positives.

Anyway, I'll try to update the civetweb sources and rebuild when I get a chance ... right now I'm on some other tasks.

**Comment by bel2125** [comment] 2017-05-31 19:35
Sorry, but for all "clang static analyzer" messages, I need the exact commit number.
Once I have it, I can analyze this quickly (like for #445), but this seems to be a different commit number than #445, since I have no error message in `set_ssl_option`

This is what I got from a `scan-build make` for the version https://github.com/civetweb/civetweb/commit/7947ec1f3d5b7a7ec83e28c23704dd1fbb64e4d4 cited by @borrrden in https://github.com/civetweb/civetweb/issues/445#issuecomment-305086238. 
```
API	Argument with 'nonnull' attribute passed null	civetweb.c	mg_get_system_info_impl	15440	7	View Report
API	Argument with 'nonnull' attribute passed null	civetweb.c	mg_get_system_info_impl	15505	19	View Report
API	Argument with 'nonnull' attribute passed null	civetweb.c	mg_get_system_info_impl	15465	17	View Report
API	Argument with 'nonnull' attribute passed null	civetweb.c	mg_get_system_info_impl	15577	21	View Report
API	Argument with 'nonnull' attribute passed null	civetweb.c	mg_get_system_info_impl	15663	23	View Report
Dead store	Dead assignment	civetweb.c	sslize	12382	1	View Report
Dead store	Dead assignment	handle_form.inl	mg_handle_form_request	645	1	View Report
Logic error	Dereference of null pointer	civetweb.c	mg_connect_client_impl	13442	12	View Report
Logic error	Dereference of null pointer	civetweb.c	mg_connect_client_impl	13447	12	View Report
```

All except the 5 false positives in `mg_get_system_info_impl` are gone in the current head version (a1341226cccc45df14feab2fb86b06292e816c52).

Or you built it with a different build option. If you could send the .html file linked in "View Report", I might be able to analyse and solve it.

**Comment by bel2125** [comment] 2017-07-29 21:49
Current commit 5817c063d884ea465c2dfa568e6e80db42cfa119 has no clang static analyser warnings.
Tested with `make clean && scan-build make WITH_IPV6=1 WITH_WEBSOCKET=1`

**Closed by bel2125** 2017-07-29 21:49 UTC
Labels: Status: waiting for info from submitter
