### ISSUE TITLE
Civetweb does not support absoluteURI

### ISSUE THREAD

**Issue by vmcloud** [civetweb/civetweb#197] opened 2015-08-31 08:58 UTC
When using civetweb as the radosgw's frontend, I found that it does not support absoluteURI, while using the http client of Golang. The similar issue has been discussed [here](https://github.com/aws/aws-sdk-go/issues/344). 
So, do we have the plan to support the absoluteURI of the http [spec](http://www.w3.org/Protocols/rfc2616/rfc2616-sec5.html#sec5.1.2)?

**Comment by bel2125** [comment] 2015-08-31 20:03
I do not really understand the discussion in your first link above (about "DreamObjects" - whatever this may be).

But according to the spec (your second link) absolute URIs are definitely required for proxies - it does not clearly state there is no need to implement it for a server. So, yes, it should be supported.

**Comment by bel2125** [comment] 2015-08-31 20:30
The form from the [`http://` spec](http://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.2.2) 
```
"http://" host [ ":" port ]  path [ "?" query ]
```
will allow a http request like
```
GET http://localhost:8080/ HTTP/1.0
```


The absolute URI form is probably also defined for ` https://`, `ws://`, and `wss://` in some other spec. Do you know about these protocols?

For https, the URI could look like this (this is what I would expect):
```
GET https://localhost:8080/ HTTP/1.0
```
or like this (but that would not work for a proxy):
```
GET http://localhost:8080/ HTTP/1.0
```

It is not like this (the protocol spec is HTTP/1.x also for https):
```
GET https://localhost:8080/ HTTPS/1.0
```

**Comment by vmcloud** [comment] 2015-09-02 08:59
Much thanks to you @bel2125, after diving into apache and other popular http servers, they can handle absoluteURI appropriately, so I think it is a flaw of civetweb.

**Comment by bel2125** [comment] 2015-09-13 20:11
Basic support for absolute URIs should be available now.
Could you test this with your client as well?

Both, the URI of the request and the URI relative to the server is available in the [interface](https://github.com/civetweb/civetweb/blob/master/include/civetweb.h#L57):
```
/* This structure contains information about the HTTP request. */
struct mg_request_info {
	const char *request_method; /* "GET", "POST", etc */
	const char *uri;            /* URL-decoded URI (full) */
	const char *rel_uri;        /* URL-decoded URI (relative) */
	...
```


So all callbacks can access the full or the relative URI.
For most callbacks, the relative uri is better than the full URI.
So it's probably better to add an additional member "request_uri" for the original URI used in the request. Only the "uri" member existed already before the first "Support absolut uri" step.

Probably the best approach is to set the "uri" member to the relative uri, so old callbacks will automatically support absolute URIs without changes.

**Comment by bel2125** [comment] 2015-09-13 21:17
I have to run some more tests to be sure all functions got correctly assigned to either the relative url or the request url.

**Comment by bel2125** [comment] 2015-09-29 20:55
CivetWeb now distinguishes between the `request_uri` and the `local_uri`.

- The `request_uri` is directly the resource string from the client request (absolute, relative or whatever).
- The `local_uri` is the resource at the local server.
 - If the `request_uri` is relative, then `request_uri == local_uri`.
 - If `request_uri` is absolute and addresses the local server, `local_uri` is the local part (without the server IP).
 - If `request_uri` is something else, `local_uri` is `NULL`. In particular, of `request_uri == "*"` or if `request_uri` addresses a different server.

Could you repeat your test with your client (Golang)?

**Comment by bel2125** [comment] 2016-02-11 20:19
I think absolute URIs work since September 2015, but I have not tested it with the Golang client myself.
I will close this issue now - if there are still some problems, please create a new one.

**Closed by bel2125** 2016-02-11 20:19 UTC
Labels: Status: done - waiting for submitter to confirm

**Comment by solaiperi** [comment] 2016-10-19 06:04
I was trying to use AWS Go SDK against Ceph (in a version where the fix https://github.com/ceph/ceph/pull/7675 is already there) and still it is not working. 

Looks like this issue still exists with civetweb.

**Comment by bel2125** [comment] 2016-10-19 18:01
Absolute URI is already implemented, and tested with the unit test for every build:
https://github.com/civetweb/civetweb/blob/master/test/public_server.c#L1433

For absolute URIs, CivetWeb additionally checks if the request is directed to the current server by cheching if the server name corresponds to the authentication_domain parameter. Did you set this parameter correctly?

I do not know ceph, and can not really comment on the discussion in ceph/ceph#7675, but from this comment https://github.com/ceph/ceph/pull/7675#issuecomment-186974518
`request_uri = http://bucket.s3.amazonaws.com/path/to/file.jpg`
The authentication domain has to be `bucket.s3.amazonaws.com`, and probably you need to check `local_uri` instead of `request_uri` (see https://github.com/civetweb/civetweb/blob/master/include/civetweb.h#L61). The implementation of absolute URIs introduced a difference between them:
```C
	const char *request_uri;    /* URL-decoded URI (absolute or relative,
	                             * as in the request) */
	const char *local_uri;      /* URL-decoded URI (relative). Can be NULL
	                             * if the request_uri does not address a
	                             * resource at the server host. */
```

**Comment by solaiperi** [comment] 2016-10-20 06:41
Thanks for the response @bel2125 

The http request is framed by AWS Go SDK, the only configuration I gave as an input to the SDK is the Endpoint. On looking at the packet trace, I don't find that authentication_domain is being sent across. But, the same code works against Apache front end for Ceph. The problem seems to be only with Civetweb.

**Comment by josear** [comment] 2016-10-20 07:58
Yesterday we upgraded to ceph (jewel) and we tried again goofys (uses AWS Go SDK). We got the same problem with the urls.
I don't know if the problem is with the ceph usage of citetweb or citetweb itself.
Btw, when using s3 the domains depends on bucket used so for bucketA domain is "bucketA.s3.example.com", for bucketB domain is "bucketB.s3.example.com". What should be "authentication_domain"? s3.example.com? *.s3.example.com?

**Comment by bel2125** [comment] 2016-10-20 18:19
I have absolutely no experience with ceph. I think the only way I can help is to provide a clear description of how civetweb should behave (and I'm rather sure it behaves like this in reality). You must judge yourself how ceph will react. Or maybe I'm interpreting the [spec in RFC2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec5.html#sec5.1.2) (from the first comment) in a way, that could be problematic for ceph: 

In my interpretation, there could be four types of valid URIs

1. "*" ... for something not directed to a specific resource
2. "/path/file.ext" ... a relative URI at the current server
3. "http://www.myserver.com/path/file.ext" ... an absolute URI at www.myserver.com
4. "http://www.myserver.com:80/path/file.ext" ... an absolute URI at www.myserver.com, port 80

... everything else is invalid (0). That's what is implemented in [get_uri_type](https://github.com/civetweb/civetweb/blob/master/src/civetweb.c#L12351) (currently line 12358 in civetweb.c, may be different later). The function also checks if the URI contains invalid letters and will also return 0 in that case. Invalid URIs are filtered, and only case 1-4 is processed further.

While the field `request_uri` is always the URI from the request, the field `local_uri` differs, as it should point to a local resource at the current server. The [further processing](https://github.com/civetweb/civetweb/blob/master/src/civetweb.c#L12937):

1. In case 1 (request_uri = "*"), local_uri will be NULL, since it does not point do a resource at the current server.
2. In case 2, request_uri == local_uri
3. see 4 (without port),
4, In case 3 and 4, we need to split protocol, server (and port) from the request_uri to get a path to the local resource, since all callbacks should see "/path/file.ext" to address their files. So local_uri is the right sub-string of request_uri after server (and port). However, civetweb does an additional check if the server is the right one. Imagine a client requests from server www.myserver.com an URI http://www.notmyserver.com/path/file.ext - I think you should not just serve /path/file.ext from www.myserver.com and ignore the *not* in www.notmyserver.com, so I decided to set local_uri to NULL, indicating the resource is not at the local server. This is done in [get_rel_url_at_current_server](https://github.com/civetweb/civetweb/blob/master/src/civetweb.c#L12445). The www.myserver.com is taken from the authentication_domain configuration parameter of civetweb - I don't know how or if this parameter is accessible for the ceph configuration.

Currently authentication_domain is a fixed parameter without wildcards, so only "bucketA.s3.example.com" will work, not "s3.example.com", not ""*.s3.example.com", not ""bucket?.s3.example.com". The authentication domain is also used for [http digest authentication](https://en.wikipedia.org/wiki/Digest_access_authentication) - there it is used as the "realm" parameter and an MD5 sum is calculated. I don't think wildcards are allowed as authentication realm (I can not tell for sure). But probably it would be OK to use s3.example.com as authentication realm and accept *s3.example.com in the absolute URI.

Maybe it would be best if you could do a short test to check if this is really an issue of different names in authentication_domain and absolute URI. A quick and dirty but effective way might be to comment the following lines in [get_rel_url_at_current_server](https://github.com/civetweb/civetweb/blob/master/src/civetweb.c#L12507):

```C
#if defined(USE_IPV6)
	if (conn->client.lsa.sa.sa_family == AF_INET6) {
		if (ntohs(conn->client.lsa.sin6.sin6_port) != port) {
			/* Request is directed to a different port */
			return 0;
		}
	} else
#endif
	{
		if (ntohs(conn->client.lsa.sin.sin_port) != port) {
			/* Request is directed to a different port */
			return 0;
		}
	}

	if ((request_domain_len != server_domain_len)
	    || (0 != memcmp(server_domain, hostbegin, server_domain_len))) {
		/* Request is directed to another server */
		return 0;
	}
```
These are the checks, if the absolute URI addresses the current server.
If it works without these checks, let's discuss how we can solve this for ceph.

**Comment by solaiperi** [comment] 2016-10-21 05:33
Thanks for the detailed explanation @bel2125. 

It appears that the Ceph's fork of Civetweb doesn't have the fix for Absolute URI. I have raised the following issue to address the same:

http://tracker.ceph.com/issues/17657

**Comment by bel2125** [comment] 2016-10-21 22:05
With 3b4792d691028647eb65d9f248102205e4e961ed I changed the way authentication_domain is used to check absolute URIs. Now s3.example.com can be used to match bucketA.s3.example.com and bucketB.s3.example.com (and s3.example.com). This might be ´useful in your case.

But if I understood the ceph tracker in your link above correctly, ceph still uses an older version of civetweb - from before the absolute URI support has been implemented. If this is the case, please test it first with a current version and open a new civetweb issue in case something does not work.

**Comment by theanalyst** [comment] 2017-01-10 18:11
@bel2125 we currently allow a set of hostnames to be valid, (as we also support static website hosting on RGW), and since we do the validation anyway, would it be ok if we have a configurable that avoids this check altogether?

**Comment by bel2125** [comment] 2017-01-11 20:58
We can do whatever helps us most.

Just to be sure: We are talking about `get_rel_url_at_current_server`, the code following 
`/* Finally check if the server corresponds to the authentication domain of the server (the server domain). ... `

Would it be useful, to have a callback with the request domain and return 0/1 to indicate if it is local?
