### ISSUE TITLE
NULL user_data passed to WebSocket data handler

### ISSUE THREAD

**Issue by NickPowers43** [civetweb/civetweb#409] opened 2017-02-03 15:04 UTC
I am passing a non-null value for the user_data parameter to mg_connect_websocket_client but I am getting a NULL value in the data callback. if I return 1 in the handler it just keeps going with a NULL value.

**Comment by bel2125** [comment] 2017-02-04 16:26
I'm doing exactly the same in the continuous integration tests ([public_server.c](https://github.com/civetweb/civetweb/blob/master/test/public_server.c)), that run for Linux, Windows and OSX after every push. 

Can you give some more details, or code snippets, so I can reproduce the problem?
Can you post the system information? (Call `civetweb -I` or use `mg_get_system_info`)? 
In particular: What version are you using?

**Comment by NickPowers43** [comment] 2017-02-04 16:39
It looks like https://github.com/civetweb/civetweb/blob/master/src/civetweb.c#L13706 is the source of the problem. When I change `NULL` to `user_data` it works fine.

**Comment by bel2125** [comment] 2017-02-04 17:02
You  mean replace `thread_data->callback_data = NULL;` by `thread_data->callback_data = user_data;`?
Since we use `newctx->user_data = user_data;`, the user data is currently available from the context ([see public_server.c](https://github.com/civetweb/civetweb/blob/master/test/public_server.c#L973)).

**Comment by bel2125** [comment] 2017-02-04 20:04
Now the user_arg is also available as argument, not only as `mg_get_user_data(mg_get_context(conn))`.

**Comment by bel2125** [comment] 2017-04-05 20:25
Changed 2 months ago - no known issues since that time ==> closing this issue.

**Closed by bel2125** 2017-04-05 20:25 UTC
Labels: Status: done - waiting for submitter to confirm
