### ISSUE TITLE
SSL don't work on ArchLinuxARM

### ISSUE THREAD

**Issue by ctucx** [civetweb/civetweb#469] opened 2017-06-14 10:42 UTC
SSL seems broken on ArchLinux ARM...
```
[le0n@alarm etc]$ sudo ../bin/civetweb ./civetweb.conf 
Loading config file ./civetweb.conf
truncating vsnprintf buffer: [,]
load_dll: libcrypto.so: cannot find CRYPTO_num_locks, CRYPTO_set_locking_callback, CRYPTO_set_id_callback, ERR_free_strings,...
Failed to start CivetWeb V1.10:
load_dll: libcrypto.so: cannot find CRYPTO_num_locks, CRYPTO_set_locking_callback, CRYPTO_set_id_callback, ERR_free_strings,...
```

```
[le0n@alarm switchsrv]$ openssl version
OpenSSL 1.1.0f  25 May 2017
```

**Comment by bel2125** [comment] 2017-06-14 18:36
I don't have an ArchLinux system running right now.

What flags did you use to make civetweb? Just "make" or some additional arguments?

Could you try to add `COPT='-DOPENSSL_API_1_1'` as make argument (or set the OPENSSL_API_1_1 define somewhere)? This tells civetweb to use the OpenSSL 1.1 API instead of the OpenSSL 1.0 (and 0.9x) API.

In case this still fails: Could you check with `objdump -T /path/to/libcrypto.so` what symbols exist, and post it here? (I don't know if "locate libcrypto.so" works for ArchLinux, to get /path/to/libcrypto.so).

**Comment by bel2125** [comment] 2017-07-03 19:23
It seems ArchLinux uses [OpenSSL 1.1](https://www.archlinux.org/packages/core/i686/openssl/), while CivetWeb defaults to OpenSSL 1.0 - to use OpenSSL 1.1, set the OPENSSL_API_1_1 define, e.g. by using `make COPT='-DOPENSSL_API_1_1'`

Please try if this solves your problem.

**Comment by bel2125** [comment] 2017-08-20 21:16
Did you try if it works with the define above?
If the problem is solved, or no longer relevant, I want to close this issue.

**Comment by user1313** [comment] 2017-10-05 23:07
I can confirm that adding COPT='-DOPENSSL_API_1_1' to the make command allowed me to run v1.10 on Debian 9. Thanks.

**Comment by bel2125** [comment] 2017-10-08 11:59
Thanks for the info.
So, ArchLinux switched to OpenSSL 1.1, while Ubuntu seems to have both 1.0 and 1.1
Sooner or later we will set the default version for CivetWeb to 1.1 as well, but currently it's 1.0

**Closed by bel2125** 2017-10-08 11:59 UTC
Labels: Status: done - waiting for submitter to confirm, Status: waiting for info from submitter
