### ISSUE TITLE
CivetServer::CivetServer(std::vector<std::string> options,...) is broken

### ISSUE THREAD

**Issue by yasushi-saito** [civetweb/civetweb#262] opened 2016-02-19 21:06 UTC
THis code

	std::vector<const char *> pointers(options.size());
	for (int i = 0; i < options.size(); i++) {
		pointers.push_back(options[i].c_str());
	}
	pointers.push_back(0);

has to be

	std::vector<const char *> pointers;
	for (int i = 0; i < options.size(); i++) {
		pointers.push_back(options[i].c_str());
	}
	pointers.push_back(0);

Otherwise there'll be NULL pointers at the beginning of pointers array.

**Comment by bel2125** [comment] 2016-02-19 22:19
It seems this interface has never been used by anyone. Personally I don't use the C++ interface at all, so thank you for this bug report.
I changed the embedded_cpp example accordingly - the issue is fixed now.

**Closed by bel2125** 2016-02-19 22:19 UTC
