### ISSUE TITLE
Question on new timout handling in read_websocket()

### ISSUE THREAD

**Issue by extergnoto** [civetweb/civetweb#569] opened 2017-12-20 11:59 UTC
I have a question: Between versions 1.9.1 and 1.20 the behaviour of read_websocket() changed. 
Before, the connection was dropped when a timeout occurred. The timeout was quite long by default (30 s).
Now, the function endlessly retries (until the socket is disconnected).
There is a TODO regarding the timout. 

Why was the old behavior changed?
What is the intended behavirour instead of the TODO?

```c
static void
read_websocket(struct mg_connection *conn,
               mg_websocket_data_handler ws_data_handler,
               void *callback_data)
{
	/* Pointer to the beginning of the portion of the incoming websocket
	 * message queue.
	 * The original websocket upgrade request is never removed, so the queue
	 * begins after it. */
	unsigned char *buf = (unsigned char *)conn->buf + conn->request_len;
	int n, error, exit_by_callback;

	/* body_len is the length of the entire queue in bytes
	 * len is the length of the current message
	 * data_len is the length of the current message's data payload
	 * header_len is the length of the current message's header */
	size_t i, len, mask_len = 0, header_len, body_len;
	uint64_t data_len = 0;

	/* "The masking key is a 32-bit value chosen at random by the client."
	 * http://tools.ietf.org/html/draft-ietf-hybi-thewebsocketprotocol-17#section-5
	*/
	unsigned char mask[4];

	/* data points to the place where the message is stored when passed to
	 * the
	 * websocket_data callback.  This is either mem on the stack, or a
	 * dynamically allocated buffer if it is too large. */
	unsigned char mem[4096];
	unsigned char mop; /* mask flag and opcode */
	double timeout = -1.0;

	if (conn->ctx->config[WEBSOCKET_TIMEOUT]) {
		timeout = atoi(conn->ctx->config[WEBSOCKET_TIMEOUT]) / 1000.0;
	}
	if ((timeout <= 0.0) && (conn->ctx->config[REQUEST_TIMEOUT])) {
		timeout = atoi(conn->ctx->config[REQUEST_TIMEOUT]) / 1000.0;
	}

	conn->in_websocket_handling = 1;
	mg_set_thread_name("wsock");

	/* Loop continuously, reading messages from the socket, invoking the
	 * callback, and waiting repeatedly until an error occurs. */
	while (!conn->ctx->stop_flag && !conn->must_close) {
		header_len = 0;
		assert(conn->data_len >= conn->request_len);
		if ((body_len = (size_t)(conn->data_len - conn->request_len)) >= 2) {
			len = buf[1] & 127;
			mask_len = (buf[1] & 128) ? 4 : 0;
			if ((len < 126) && (body_len >= mask_len)) {
				/* inline 7-bit length field */
				data_len = len;
				header_len = 2 + mask_len;
			} else if ((len == 126) && (body_len >= (4 + mask_len))) {
				/* 16-bit length field */
				header_len = 4 + mask_len;
				data_len = ((((size_t)buf[2]) << 8) + buf[3]);
			} else if (body_len >= (10 + mask_len)) {
				/* 64-bit length field */
				uint32_t l1, l2;
				memcpy(&l1, &buf[2], 4); /* Use memcpy for alignment */
				memcpy(&l2, &buf[6], 4);
				header_len = 10 + mask_len;
				data_len = (((uint64_t)ntohl(l1)) << 32) + ntohl(l2);

				if (data_len > (uint64_t)0x7FFF0000ul) {
					/* no can do */
					mg_cry(conn, "websocket out of memory; closing connection");
					break;
				}
			}
		}

		if ((header_len > 0) && (body_len >= header_len)) {
			/* Allocate space to hold websocket payload */
			unsigned char *data = mem;

			if ((size_t)data_len > (size_t)sizeof(mem)) {
				data =
				    (unsigned char *)mg_malloc_ctx((size_t)data_len, conn->ctx);
				if (data == NULL) {
					/* Allocation failed, exit the loop and then close the
					 * connection */
					mg_cry(conn, "websocket out of memory; closing connection");
					break;
				}
			}

			/* Copy the mask before we shift the queue and destroy it */
			if (mask_len > 0) {
				memcpy(mask, buf + header_len - mask_len, sizeof(mask));
			} else {
				memset(mask, 0, sizeof(mask));
			}

			/* Read frame payload from the first message in the queue into
			 * data and advance the queue by moving the memory in place. */
			assert(body_len >= header_len);
			if (data_len + (uint64_t)header_len > (uint64_t)body_len) {
				mop = buf[0]; /* current mask and opcode */
				/* Overflow case */
				len = body_len - header_len;
				memcpy(data, buf + header_len, len);
				error = 0;
				while ((uint64_t)len < data_len) {
					n = pull_inner(NULL,
					               conn,
					               (char *)(data + len),
					               (int)(data_len - len),
					               timeout);
					if (n <= -2) {
						error = 1;
						break;
					} else if (n > 0) {
						len += (size_t)n;
					} else {
						/* Timeout: should retry */
						/* TODO: retry condition */
					}
				}
				if (error) {
					mg_cry(conn, "Websocket pull failed; closing connection");
					if (data != mem) {
						mg_free(data);
					}
					break;
				}

				conn->data_len = conn->request_len;

			} else {

				mop = buf[0]; /* current mask and opcode, overwritten by
				               * memmove() */

				/* Length of the message being read at the front of the
				 * queue. Cast to 31 bit is OK, since we limited
				 * data_len before. */
				len = (size_t)data_len + header_len;

				/* Copy the data payload into the data pointer for the
				 * callback. Cast to 31 bit is OK, since we
				 * limited data_len */
				memcpy(data, buf + header_len, (size_t)data_len);

				/* Move the queue forward len bytes */
				memmove(buf, buf + len, body_len - len);

				/* Mark the queue as advanced */
				conn->data_len -= (int)len;
			}

			/* Apply mask if necessary */
			if (mask_len > 0) {
				for (i = 0; i < (size_t)data_len; i++) {
					data[i] ^= mask[i & 3];
				}
			}

			/* Exit the loop if callback signals to exit (server side),
			 * or "connection close" opcode received (client side). */
			exit_by_callback = 0;
			if ((ws_data_handler != NULL)
			    && !ws_data_handler(conn,
			                        mop,
			                        (char *)data,
			                        (size_t)data_len,
			                        callback_data)) {
				exit_by_callback = 1;
			}

			if (data != mem) {
				mg_free(data);
			}

			if (exit_by_callback
			    || ((mop & 0xf) == WEBSOCKET_OPCODE_CONNECTION_CLOSE)) {
				/* Opcode == 8, connection close */
				break;
			}

			/* Not breaking the loop, process next websocket frame. */
		} else {
			/* Read from the socket into the next available location in the
			 * message queue. */
			n = pull_inner(NULL,
			               conn,
			               conn->buf + conn->data_len,
			               conn->buf_size - conn->data_len,
			               timeout);
			if (n <= -2) {
				/* Error, no bytes read */
				break;
			}
			if (n > 0) {
				conn->data_len += n;
			} else {
				/* Timeout: should retry */
				/* TODO: get timeout def */
			}
		}
	}

	mg_set_thread_name("worker");
	conn->in_websocket_handling = 0;
}
```

**Comment by bel2125** [comment] 2017-12-20 21:59
> I have a question: Between versions 1.9.1 and 1.20 the behaviour of read\_websocket() changed.

You mean 1.10?

> There is a TODO regarding the timout.

You mean this TODO:

```C
				/* Timeout: should retry */
				/* TODO: get timeout def */
```
or that one:
```C
						/* Timeout: should retry */
						/* TODO: retry condition */
```

Both were added here: 
https://github.com/civetweb/civetweb/commit/88d885d309d467df5ca3f6b10236c7964d5f338d

> Why was the old behavior changed?

From the old commit comment, it was a fix for websockets using TLS (wss): There were sporadic disconnects if network packets were fragmented in a way there is data on the network, but not enough to decrypt a single byte.

... if these are the changes you meant.

> What is the intended behavirour instead of the TODO?

Repeat until some higher layer decides we tried long enough (not the low level SSL layer or pull / pull\_inner). There must be some new timer in read\_websocket - if we tried long enough there must be some code to forcibly close the connection.

**Comment by extergnoto** [comment] 2017-12-21 09:15
I meant both TODOs.

If I understand it right: 
In pull_inner the the network pull returns fast, but ssl returns length 0 indicating timeout (return -1).
This is interpreted in read_websocket as a timout, but WEBSOCKET_TIMEOUT hasn´t elapsed yet.
A possible solution is like in pull_all I guess, using an additional loop.

Unfortunately pull_all uses the REQUEST_TIMEOUT always. So maybe there should be an additional function to be used from pull_all and read_websocket (see below). 

```c
static int
pull_all_timeout(FILE *fp, struct mg_connection *conn, char *buf, int len, double timeout)
{
	int n, nread = 0;
	uint64_t start_time = 0, now = 0, timeout_ns = 0;

	if (timeout >= 0.0) {
		start_time = mg_get_current_time_ns();
		timeout_ns = (uint64_t)(timeout * 1.0E9);
	}

	while ((len > 0) && (conn->ctx->stop_flag == 0)) {
		n = pull_inner(fp, conn, buf + nread, len, timeout);
		if (n == -2) {
			if (nread == 0) {
				nread = -1; /* Propagate the error */
			}
			break;
		} else if (n == -1) {
			/* timeout */
			if (timeout >= 0.0) {
				now = mg_get_current_time_ns();
				if ((now - start_time) <= timeout_ns) {
					continue;
				}
			}
			break;
		} else if (n == 0) {
			break; /* No more data to read */
		} else {
			conn->consumed_content += n;
			nread += n;
			len -= n;
		}
	}

	return nread;
}

static int
pull_all(FILE *fp, struct mg_connection *conn, char *buf, int len)
{
	double timeout = -1.0;
	if (conn->ctx->config[REQUEST_TIMEOUT]) {
		timeout = atoi(conn->ctx->config[REQUEST_TIMEOUT]) / 1000.0;
	}
        return pull_all_timeout(fp, conn, buf, len, timeout);
}
```

**Comment by extergnoto** [comment] 2017-12-21 09:26
pull_inner is used at some more places. Maybe the same problem can occur?

**Comment by bel2125** [comment] 2017-12-21 23:24
The solution is probably much easier in `pull_inner`, without adding yet another layer.

```C
			nread = SSL_read(conn->ssl, buf, len);
			if (nread <= 0) {
				err = SSL_get_error(conn->ssl, nread);
*** handle the case nread == 0, but no error here ***
				if ((err == SSL_ERROR_SYSCALL) && (nread == -1)) {
					err = ERRNO;
				} else if ((err == SSL_ERROR_WANT_READ)
				           || (err == SSL_ERROR_WANT_WRITE)) {
					nread = 0;
				} else {
					DEBUG_TRACE("SSL_read() failed, error %d", err);
					return -2;
				}
			} else {
				err = 0;
			}
```

Unfortunately I know no way to systematically reproduce and test this situation.

**Comment by bel2125** [comment] 2018-01-15 23:31
I kind of forgot that issue the end of last year.
Did you do any further tests?

In the meantime I added websocket ping/pong support, so websocket timeouts need to be considered in a different way for the new version.

Is this still relevant for you?

**Comment by extergnoto** [comment] 2018-01-22 10:04
The issue is still relevant.
I have a system with quite limited resources (e.g. number of socket connections).
Therefore it is desirable to detect a non-responding client (client crashed or physically disconnected) within the defined timeout. Otherwise one must rely on the underlying socket timeout which is quite long usually.
A ping-pong-timeout can probably detect a non-responding client much faster, which is good. 

Unfortunatly I cannot test the master at the moment. I must stay with 1.10, but I can live with the current behaviour, as I have implemented the workaroud from above  mg_pull_inner_timeout.

Nevertheless I think it is still a good idea, to always have the same timeout in read_websocket. I always found it risky to rely on some higher level mechanism within a lower layer, because it injects some unwanted dependencies.

**Comment by krzk** [comment] 2019-03-19 11:22
If I understand this report correctly, I am hitting exactly the same issue. I have a server for websockets with websocket_timeout_ms (30 s). Before, after lack of communication the connection was closed nicely. Now (v1.11, 0e30feff3832963e7321223972ac05cc6f04ac06, e8bd61bb8f0689015083185fe01c98a93b0e1c49) the connection simply does not timeout.
I added request_timeout_ms but it did not help.

I need the timeout because websocket clients can disappear without closing the connection. Server still thinks that client is connected but he is long time gone. It is a easy way to DoS the server.

**Comment by bel2125** [comment] 2019-03-22 18:26
`pull_inner` returns -2 for errors and -1 for timeout - except [here](https://github.com/civetweb/civetweb/blob/a714efa0a0f36607f70226f75269cd3f9361204b/src/civetweb.c#L6386) ... it returns -1 on this error ... I'm going to set this to -2 as well.

@krzk : For websockets, I would use the ping pong mechanism - option "enable_websocket_ping_pong" to "yes", and "websocket_timeout_ms" to "30000". So the server notices when a client is gone after around 30 seconds.

**Comment by bel2125** [comment] 2020-09-21 12:23
Question has been answered long ago, but it was forgotten to close this issue.

**Closed by bel2125** 2020-09-21 12:23 UTC
