### ISSUE TITLE
civetweb server doesn't response to any WS request. Browser show 'Provisional headers are shown'

### ISSUE THREAD

**Issue by quhezheng** [civetweb/civetweb#944] opened 2020-11-20 05:44 UTC
civetweb server app has been running for couple of days without any issue. 

Today  WS request submitted from Chrome can't get any response,Chrome log show 'Provisional headers are shown'.  
The civetweb server app log shows mg_websocket_write() return <0. 
std::strerror(errno) is 'Broken pipe'

We restarted the civetweb server app, and  the issue was gone. 
I'm afraid this would happen again.  What could be the root cause?

**Comment by bel2125** [comment] 2020-11-20 17:05
Hard to say without any further details.
"Broken pipe" usually means the other side stopped communicating without closing the connection properly, or the network in-between broke down. 
Are you writing to one client or to multiple?

**Comment by bel2125** [comment] 2020-11-20 17:15
It seems "provisional headers are shown" is or was normal for websockets ([chrome issue 327581](https://bugs.chromium.org/p/chromium/issues/detail?id=327581)). I rarely use the Chrome devtools, so I'm not exactly sure where and when you get the "provisional headers" message - could be that you only get this message as long as you did not get any response for your request. Did you check the server system in the situation the server was not responding, e.g., maybe all resources were used up?
What operating system and civetweb version are you using?

**Comment by quhezheng** [comment] 2020-11-23 11:56
> Hard to say without any further details.
> "Broken pipe" usually means the other side stopped communicating without closing the connection properly, or the network in-between broke down.
> Are you writing to one client or to multiple?

My code was writing to only one client

**Comment by quhezheng** [comment] 2020-11-23 12:02
> aybe all resources were used up?

The Chrome client can't send out any data to server when get the "provisional headers" message. I guess the socket connection can't be established. Not only  Chrome client but also civetweb client can't connect to server as well. But rebooting civetweb server app can fix the issue.

The system resource was rich enough at the moment. 
It's running on Ubuntu 18.04.  civetweb-1.11

**Comment by bel2125** [comment] 2020-11-25 15:58
V1.11 is more than two years old. Probably there is a fix available in the current version. There was some rare, not reproducible bug, fixed in V1.12 (see [release notes](https://github.com/civetweb/civetweb/blob/master/RELEASE_NOTES.md)):
- Fixes for the request queue (rare loss of requests)
I can't tell if this is related to websockets in any way. For a sporadic problem without any logs, I can only provide an educated guess.

**Comment by bel2125** [comment] 2021-11-21 15:11
Not enough information for analysis.
No new information since about a year.
--> closing this issue

**Closed by bel2125** 2021-11-21 15:11 UTC
Labels: Status: waiting for info from submitter
