### ISSUE TITLE
FreeBSD build errors. - Travis CI integration for CivetWeb on FreeBSD

### ISSUE THREAD

**Issue by Parakleta** [civetweb/civetweb#200] opened 2015-09-10 04:58 UTC
The build script uses `#!/bin/sh` but then calls `set -o pipefail`.  These are incompatible.  Either use `#!/usr/local/bin/bash` or similar or drop the `-o` option to `pipefail`.

Casting `pthread_t` to `unsigned long` fails in the compiler.  This related code should be upgraded to use the correct `CRYPTO_THREADID_` semantics.  Failing that, just using the default (thread-local `errno` behaviour) is sufficient.

I gave up with problems patching `luasqlite` and went back to v1.7 so there may be other problems.

**Comment by Parakleta** [comment] 2015-09-10 05:02
The `pthread_t` to `unsigned long` exists in v1.7 as well, but it doesn't fail there I think because `-Werror` isn't set.

**Comment by bel2125** [comment] 2015-09-10 21:48
This sizeof(pthread_t) > sizeof(unsigned long) problem is something I just found recently when trying to get the MacOS build running on TravisCI. It always gave me this compile error with clang for MacOS:

```
/Users/travis/build/civetweb/civetweb/src/civetweb.c:9557:24: error: cast from function call of type 'pthread_t' (aka 'struct _opaque_pthread_t *') to non-matching type 'unsigned long' [-Werror,-Wbad-function-cast]
        return (unsigned long)pthread_self();
                              ^~~~~~~~~~~~~~
1 error generated.
```

All other compiler at all other systems did not seem to care - either because pthread_t is the same size as unsigned long, or the compilers did not detect the problem.
I tried to solve the problem yesterday, but my attempts did not work properly on all systems up to now. So I finally restored the previous behavior and added a TODO mark in the code.

Maybe just try again with the current version - the version of yesterday was just in the middle of some not working fixes for this problem.

I also considered using the new API, but this did not exist in openSSL versions before 1.0.0 - and these versions are still in use. I also considered to remove the function completely (you can test this with the `#define pthread_t_LARGER_THAN_unsigned_long`), which will lead to the default behavior (e.g., address of `errno`), but I did not finish reading all material and I did not check the minimum version required.

**Comment by bel2125** [comment] 2015-09-10 21:49
Apart from sizeof(pthread_t) > sizeof(unsigned long):
Are there any other problems?

> I gave up with problems patching luasqlite and went back to v1.7 so there may be other problems.

**Comment by Parakleta** [comment] 2015-09-10 22:21
MacOS and FreeBSD both use the clang compiler instead of GCC, and actually both come from a common code base, so it's not surprising they both fail the same way.  I looked through the OpenSSL stuff and it's pretty bad in general, so the default behaviour is no worse than you could achieve manually.  The problem is that even if you do everything properly by their API there is no way to use `pthread_equal` in the place of `CRYPTO_THREADID_cmp`, so `errno` is actually a better approximation to thread ID than comparing the pointers of an opaque structure.

**Comment by Parakleta** [comment] 2015-09-10 22:29
There was the `set -o pipefail` issue.

I got stuck with an error trying to copy a luasqlite `CMakeList.txt` that didn't exist.  I assumed the build system was in flux and I don't know enough about CMake to diagnose the issue.  I can try again in the future.

**Comment by bel2125** [comment] 2015-09-11 16:53
>  I assumed the build system was in flux 

Yes, the CMake system is just in a setup phase - the setup is monitored here: https://github.com/civetweb/civetweb/issues/94

I just temporarily deactivated the MacOS build on the continuous integration (CI) environment yesterday, because currently the build always fails, and status [on the main page](https://github.com/civetweb/civetweb) always shows "build failed", although everything just works fine for Linux.
First the build needs to be fixed - it makes no sense to run >200 different builds for MacOS for every commit if I already know they will fail.
I have no Mac available, but I have a FreeBSD VM somewhere, so maybe it would make sense to do some tests there to get the MacOS build running. I don't know how similar or different their APIs might be.

**Comment by bel2125** [comment] 2015-09-11 17:01
> ... so errno is actually a better approximation to thread ID ...

I tend to remove call to the `CRYPTO_set_id_callback` function, so openSSL should use the default behaviour. I'm just currently not sure in what cases this might not be sufficient - why did them make this function?

**Comment by Parakleta** [comment] 2015-09-11 22:38
I think the function exists because it works in Linux and Windows.  There is this common mistake where developers assume that Linux === Posix, rather than reading the actual Posix standards.  The result is code with Linux-isms that don't work on Linux in general.  The `CRYPTO_THREAD_` functions are an attempt to fix the shortcomings with `CRYPTO_set_id_callback` but unfortunately they're still wrong.  The issue now is that they're comparing pointer addresses for the `pthread_t` structure but it is possible by the standard to have two different structures with the same value since deep comparison using `pthread_equal` is required.

`errno` is equally incorrect but simpler to implement.  Each thread is required to have a unique *value* for `errno` but this doesn't require they have unique addresses.  You're screwed either way.

**Comment by bel2125** [comment] 2015-09-12 19:29
If there is no simple standard solution, I could still add my own `unsigned long` variable to the [thread local storage](https://en.wikipedia.org/wiki/Thread-local_storage). CivetWeb uses either Windows threads or pthreads. There is no problem with Windows here, since GetCurrentThreadId will return a DWORD. If pthreads are used, I can [add a 4 byte thread ID to the thread local storageon my own](https://en.wikipedia.org/wiki/Thread-local_storage#Pthreads_implementation) with [`pthread_setspecific`](http://pubs.opengroup.org/onlinepubs/009695399/functions/pthread_getspecific.html).

**Comment by Parakleta** [comment] 2015-09-12 22:54
Thread Local Storage will be a good robust solution.

Regarding the similarities between OSX and FreeBSD, OSX forked the FreeBSD userland way back when and there has been a lot of code sharing ever since.  FreeBSD will be the closest to OSX and should work quite well as a first approximation.

**Comment by bel2125** [comment] 2015-09-20 20:29
Now, for TravisCI all builds are OK again. 
The SSL-id function became rather complicated, with special cases for Windows, systems/compilers with `sizeof(unsigned long) < sizeof(pthread_t)` and systems with `sizeof(unsigned long) >= sizeof(pthread_t)`. Could you test it again for your case.

**Comment by Parakleta** [comment] 2015-09-21 00:19
My internet has crapped out and it may be up to a week before it comes back properly (although with luck I'll have it fixed tomorrow).  I'll test once I'm properly back online.

**Comment by Parakleta** [comment] 2015-09-23 05:36
The assumption that `/bin/sh` === `/bin/bash` is still causing the build script to fail.

The `pthread_t` cast still fails I think just by the fact that it exists.  The cast may work on Linux but it is against the specification and I think if you have a working solution which complies with the spec you should use it for all posix systems.

I cannot get CMake to respect my proxy settings, and when I use `ccmake .` to enable Lua it complains:

    file attempted to create a directory:
    .../civetweb/output/build/third_party/src/lua-stamp
    into a source directory.

I've never really taken to CMake, it always seemed very complicated and I could never figure it out and so I have always stuck with SCons.

**Comment by bel2125** [comment] 2015-09-23 19:17
Probably FreeBSD should be considered in the CMake build system port (issue #94).
I don't know if it is possible to add it to the Travis CI tests.

Regarding pthread_t: It seems there is no working solution which complies with the posix spec - the old SSL API seems fundamentally broken here, and I currently can not assume the new one is available in all cases. Probably using a cast through a void *, and effectively copying typeless data with memcpy is the only way to completely avoid compile warnings.

**Comment by Parakleta** [comment] 2015-09-23 22:24
I've been looking into this a bit more, would you consider making LibTLS a dependency in the same way that Lua is?  This would resolve all of these problems and would let you make a smaller static binary and would be ideal for embedded applications.  I may look into this myself at some later date.

Failing that, given that you're trying to maintain compatibility with old OpenSSL implementations maybe the split should be on OpenSSL version and not on `pthread_t` size.  That is, use the new `CRYPTO_THREAD_` functions where available and the deprecated ones where necessary.  I think it's probably fine to say FreeBSD + OpenSSL < 1.0.1 is just unsupported so long as >=1.0.1g works.

**Comment by bel2125** [comment] 2015-09-24 19:17
I will have a look into LibTLS.

The problem is, CivetWeb can load openssl library dynamically, so the OpenSSL version can only be determined at runtime. Thus, the code will still have to have both versions at compile time, just like now. So this will not help for a compile error. The compiler does not understand the program logic at this point, and there is no way use the preprocessor for it - so the compiler raises an error at a point where there is no error, because the code can not be reached. Using memcpy will avoid any compiler check.

**Comment by Parakleta** [comment] 2015-09-24 22:07
Even if you load at runtime you still compile against a set of symbols and if those symbols change I think you're allowed to throw a runtime error.  You can test the `OPENSSL_VERSION_NUMBER` define at compile time to choose behaviour, and obviously every OS has identifying `#define`s so between those things it should be possible to choose the best behaviour.

**Comment by bel2125** [comment] 2015-09-25 16:30
Do you have a specific idea, how the SSL ID callback function would look like in this case?
Could you provide a code snippet?

**Comment by bel2125** [comment] 2015-09-25 17:13
Unfortunately, the straight forward implementation
`#if sizeof(unsigned long) < sizeof(pthread_t)`
can not be used. This is a restriction of the C preprocessor, as already mentioned.

- Then there are a lot of different [64-bit data models](https://en.wikipedia.org/wiki/64-bit_computing#64-bit_data_models). The model depends on the operating system, but even more on the compiler. So for one operating system, different compilers may use different 64 bit data models - hurray! 
- There is no standard #define, supported by all compilers to check which 64 bit model is used - hurray again!
- As far as I know, the POSIX standard does not define what has to be behind pthread_t, so it could be short, int, long, pointer, whatever. Probably different systems use different base types - did I already say hurray?
- And pthread is also not a operating system library, but usually a layer above operating system native threads, so in theory different pthread libraries on the same system with the same compiler might also choose different pthread_t types - I think for Windows there are different pthread emulation libraries, probably not for other systems, I don't know. To be 100% formally correct, this should be taken into account as well - but maybe this part of the problem can be ignored for all cases of practical relevance.

If anyone has any idea how to deal with these unaligned standards at compile time with some #if conditions, please tell me.

**Comment by Parakleta** [comment] 2015-09-25 23:04
The best I can find is to put your old `CRYPTO_setid_callback` inside a  `#if OPENSSL_VERSION_NUMBER < 0x010000000` and then trust the default behaviour being correct for newer versions.  You really have no other choice that I can see unless/until you move to LibTLS.

Effectively for old versions there is no way to be correct and you'll have to assume that the OSs affected by the `pthread_t` issue have moved to the newer version.  Even with the new version the API is rubbish and so you cannot really implement anything that is correct, but OpenSSL claim to have a default/automatic behaviour which you will just have to trust and assume at least that it's being used by enough people that there isn't a problem with it (which totally worked for HeartBleed).  I think trying to implement a custom solution on top of their API is going to be brittle and is just going to expose you to potential problems in the future.

Regarding 64 bit I think the `__LP64__` and associated macros are reasonably widely supported, except on Windows.
Regarding `pthread_t` the POSIX standard explicitly defines it as opaque.

Moving to LibTLS in the future will solve all of these problems because it is inherently thread-safe.

**Comment by Parakleta** [comment] 2015-09-25 23:15
I might be able to look at doing the code changes associated with LibTLS but someone else would need to look at integrating it with your build system.  I'll see if I can free up a few hours tomorrow to fork the project, with a little luck it may be a simple change to implement.

**Comment by Parakleta** [comment] 2015-10-07 23:21
It's not going to be simple to implement the change to LibTLS, and on further investigation the benefits are going to be very marginal.  I had thought LibTLS was its own project, but it turns out it depends on OpenSSL anyway (actually LibreSSL/BoringSSL, the OpenBSD post-heartbleed fork) and is basically just a wrapper, so nothing is gained there.

I have discovered that I can build the project successfully with the old makefiles which are still kicking around so there must be a different compile flag in the CMake system which is throwing the error.

**Comment by bel2125** [comment] 2015-10-08 18:39
I will still maintain the current Makefile at least until the CMake transition is completed.
So the next release will have a working Makefile and a working CMake.
Then we can think about removing the old Makefile, or generating it automatically from CMake.

You found a way to compile the project on FreeBSD?

**Comment by Parakleta** [comment] 2015-10-08 23:04
If I type `gmake` in the root of the project it works.  I cannot get anything related to the build script or CMake to work, there are just too many errors and I don't know enough about CMake to diagnose/fix them.

**Comment by bel2125** [comment] 2015-10-09 18:11
Could you try `gmake WITH_IPV6=1 WITH_WEBSOCKET=1 WITH_LUA=1` ?

**Comment by Parakleta** [comment] 2015-10-11 23:22
There's a few warnings in third party but otherwise everything is fine.

**Comment by bel2125** [comment] 2015-10-12 17:23
OK. Thank you.
These flags should compile CivetWeb with all options ready for use in released versions (in addition, there would be some options I'm currently working on like WITH_DUKTAPE=1 or WITH_SSJS=1 - it's probably too early to use them now).

Warnings in third party components will not be fixed here.

So, what else can I do here?

**Comment by Parakleta** [comment] 2015-10-12 20:39
Basically the only issue is that the `build.sh` script and `CMake` system don't work on FreeBSD currently.

**Comment by bel2125** [comment] 2015-10-12 20:56
I'm also not the expert on CMake and certainly not on FreeBSD.

The CMake issues are collected in #94.

**Comment by bel2125** [comment] 2015-10-12 21:01
Issue #94 (Port the build system to cmake) is used to track the required changes.

I will give feedback here once it is done.

**Comment by bel2125** [comment] 2016-05-19 19:36
The CMake system is working now, and Travis CI can be used to build CivetWeb for Linux and OSX.
However, it seems Travis is not going to support a hosted CI environment for FreeBSD soon (I found this issue: https://github.com/travis-ci/travis-ci/issues/1818, I don't know if this is still up to date). Maybe there is an alternative hosted build for FreeBSD - although I would not really be happy if there is a third build environment (in addition to Travis and AppVeyor) that needs to be supported.
It the build for FreeBSD is just fixed one time and not integrated in a continuous integration (CI) environment, it is quite likely that the build or some integration tests will break again after a couple of dozen commits. It is certainly possible to use CivetWeb in FreeBSD, but I cannot automatically check it for every commit.

So it's not really duplicated to the CMake issue anymore, but I don't see a chance to support FreeBSD with the same quality as Linux in the moment, since there is no CI environment.

**Comment by bel2125** [comment] 2016-07-09 09:05
I just found a project idea to integrate a FreeBSD build system in Travis CI in at the [FreeBSD IdeasPage](https://wiki.freebsd.org/IdeasPage#Travis_Continuous_Integration_Support_for_FreeBSD)
(last edited 2016-06-29 13:43:16):

> `Travis Continuous Integration Support for FreeBSD
>
>Technical Contact: rodrigc@,
>
>Description
>
>Travis Continuous Integration is a very popular Continuous Integration system used by projects hosted on GitHub. If a GitHub project has a .travis.yml config file in the root directory, the Travis system will build and test the project if new code is committed to the GitHub project.
>
> Currently, Travis only supports Linux and MacOS X. The Travis project closed issue 1818 which was a request to add FreeBSD support to Travis, due to lack of resources. However, having this support would be very useful, and allow FreeBSD to test many third party projects on GitHub. 

Once this is available, we should have a FreeBSD continuous integration as well. Then all build errors can be found and solved immediately.

**Comment by bel2125** [comment] 2016-07-09 09:17
I created a new label type for external dependencies - I can not solve this on my own.
I also renamed the issue, so one can see at first sight what should be done with this issue and what what third party project is required.

**Closed** 2022-02-22 16:49 UTC
Labels: Status: blocked - depending on third party project

**Comment by bel2125** [comment] 2022-02-22 17:27
For your information: Finally Travis CI decided to provide a FreeBSD build environment. We now have a unit test running on FreeBSD as well.
