### ISSUE TITLE
Error with init_ssl callback

### ISSUE THREAD

**Issue by Astaelan** [civetweb/civetweb#524] opened 2017-09-28 01:55 UTC
I do not know if this still exists on 1.10, but with the 1.9.1 release when you provide a callback for init_ssl and simply return 0, a normal HTTP request (without SSL) fails.
You can assume that no options have been set, so there is no SSL certificate supplied, but it seems to impact whether it'll still accept normal HTTP requests.
I can reproduce this by only providing the init_ssl callback and returning 0 with nothing else in the callback, then attempting to access a Lua server page on disk via http://

**Comment by bel2125** [comment] 2017-09-28 18:29
`callbacks.init_ssl` is called when the server starts.

If the callback returns 0, CivetWeb initializes OpenSSL
If it returns 1, CivetWeb assumes the calback already did this
If it returns -1, initializing fails and web server will not not start

> You can assume that no options have been set ...

If you don't have anything configured, you are using the standard `listening_port 8080`, so there is no need to initialize OpenSSL, and the callback should not be called at all.

Have you configuration `listening_port 443s` (or some other port number + 's').

**Comment by Astaelan** [comment] 2017-09-29 22:34
Yes. The callback returns 0, but there is no SSL configuration. This was intended. I was simply adding empty callback stubs in preparation for more down the road.  However, the issue is not related to SSL explicitly.
The issue is that if you override the init_ssl and return 0, you would expect the same behaviour as if you didn't override the callback at all. That is not the case.
When you override init_ssl and just return 0, and don't have any SSL configuration supplied, the entire civetweb stack fails. It will no longer serve normal HTTP requests, which it would if you did not override init_ssl to do nothing.
The reason this came up, is because I am overriding all the callbacks in a library that will wrap civetweb functionality. So I expected to be able to override all the callbacks, supply the correct "do nothing" return value and have civetweb operate as if there was no callbacks supplied.  It's more an annoyance, as I don't think I need to override init_ssl, but it's a contradiction in behaviour from what would be expected.
All other callbacks with returns can return some value that lets civetweb still operate as if the callback never happened, init_ssl is the only exception that breaks stuff when you return 0.

**Comment by bel2125** [comment] 2017-10-01 19:52
I don't think it's an exception, but probably we are still not at the point. There are 3 scenarios:


1 SSL port is not configured
===

If `listening_ports` does not contain any secure port (there are only numbers an `,` in this string, no lettern), SSL is not required.

The `init_sll` callback should not be called, and `ssl_certificate` is ignored.

Is this your situation? 
Is "init_ssl" called?


2 SSL port is configured but no certificate 
===

If, `listening_ports` is `443s` (or some other port number + `s`) and `ssl_certificate` is not set, the server cannot start. If you try this with the standalone server, you get an error message
```
Cannot add SSL socket (entry 1). Is -ssl_certificate option set?
Failed to start CivetWeb V1.10:
Cannot add SSL socket (entry 1). Is -ssl_certificate option set?
```
(yes, one line is duplicate ... that's a minor issue I should take care some time). The standalone server does not add any callback. You will get the same result for `listening_port 80,443s` (except, you get "entry 2" instead of "entry 1").

If you add a callback, you do not have to have the `ssl_certificate` configuration, since you might use the callback to set up the certificate. But if you don't provide this configuration and don't have the certificate set up correctly in the callback, the entire server initialization fails, just like for `listening_port 80,443s` without callback. 

This is actually not a bug, but works as designed.

It may not be well documented, but as a general rule, if you provide one port number with `r` or `s` in `listening_ports`, you have to provide a valid `ssl_certificate`. 
The only exception allowing to omit `ssl_certificate` is to have a complex callback doing this work - and this option mainly exists for legacy reasons. This callback is definitely not a simple `return 0`, and I definitely not recommend using an SSL port without `ssl_certificate`, since this callback is a very advanced option.


3 SSL port and certificate are configured
===

If there is an SSL port in `listening_ports`, and `ssl_certificate` is configured correctly, the callback should work just as expected. Returning 0 should exactly do what's expected.

?
===

So, what **exactly** did you configure for `listening_ports` and `ssl_certificate`?

**Comment by bel2125** [comment] 2017-10-01 20:28
I did some tests, and it seems `init_ssl` is called even if it's not required.
So it's probably case 1 above.

**Comment by Astaelan** [comment] 2017-10-02 03:26
Yes, scenario #1 was the case, and it sounds like you fixed it.
This should stop the stack from failing on HTTP when SSL isn't used but the callback is assigned, thanks.

**Comment by bel2125** [comment] 2017-10-02 17:59
So, since it's fixed, we can close this issue.

By the way: Be careful with using `#1` (or any #+number) on GitHub: It's a link to the first issue (issue with that number).

**Closed by bel2125** 2017-10-02 17:59 UTC
