### ISSUE TITLE
Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH when running embedded_cpp.cpp

### ISSUE THREAD

**Issue by xeoshow** [civetweb/civetweb#422] opened 2017-02-26 10:22 UTC
Hello, 

I have succesfully compiled and run embedded_cpp.cpp in my QT Qt5.5.1-mingw492 environment using below: 
https://github.com/civetweb/civetweb/blob/master/examples/embedded_cpp/embedded_cpp.cpp

And now I have put my index.html and its dependency files like css, js, image files to the DOCUMENT_ROOT folder, the index.html file itself can be loaded into my chrome browser but got below error in chrome console. All the files are correctly placed in the corresponding path. 

What is missing and how should I resolve the problem? I tried the precompiled binary files CivetWeb_Win32+64_V1.9.1.zip and it works very well, confused what is missing from my side...

Any help is highly appreciated!

> **Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH
http://localhost:8081/static/css/AdminLTE.min.css Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH
http://localhost:8081/static/js/plugins/jQuery/jQuery-2.2.0.min.js Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH
http://localhost:8081/static/js/plugins/bootstrap/bootstrap.min.js Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH
app.min.js:13 Uncaught Error: AdminLTE requires jQuery
    at app.min.js:13
http://localhost:8081/static/js/vendor.ad881d6cc3a38d459a3a.js Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH
http://localhost:8081/static/js/app.f2ad0f34e4204ad3234c.js Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH**

**Comment by xeoshow** [comment] 2017-02-26 13:38
By a simple search in current Repo, I found my issue seems quite similar to:
https://github.com/civetweb/civetweb/issues/417

But there is no need to refresh my index.html, everytime I open, it got this problem...

My index.html is 2kb, js files about less than 1MB per file, css about 2kb...

**Comment by xeoshow** [comment] 2017-02-26 14:03
Just downloaded civetweb-1.8.zip from below:
https://github.com/civetweb/civetweb/releases

and also set NO_CACHING, while the compiled result exe works great! Other things are all the same, html/js/css and chrome!

**Comment by bel2125** [comment] 2017-02-26 19:35
I was unable to reproduce #417 - could you explain in detail how you reproduce the content length mismatch?

What version are you using exactly? 
Can you print the system information? (call `civetweb -I`)
What file are you loading to reproduce the problem (exact size and file extension)?

**Comment by xeoshow** [comment] 2017-02-26 23:45
CivetWeb.exe -I

>CivetWeb V1.10 (CivetWeb V1.10)
Server Version: 1.10
Windows 6.2
CPU: type 0, cores 8, mask ff
Features: C1F
 Files HTTPS CGI IPv6 WebSockets
Build: Feb 26 2017
MinGW32: 3.11
Data model: int:2/4/4/8, float:4/8/12, char:1/2, ptr:4, size:4, time:4

**Comment by xeoshow** [comment] 2017-02-26 23:49
Not sure how to upload files, just simple index.html and related js\css files. If you could provide email or somewhere I can send all things to you to have a look.

Browser is Google Chrome 53.0.2785.101 m.

Yes, localhost.

My steps are simple:
1. GIT from github.com
2. import to the QT Qt5.5.1-mingw492 
3. set NO_CACHING
4. compile and run
5. open ulr http://localhost:8081 in chrome, problem occur.

**Comment by bel2125** [comment] 2017-02-28 20:45
I just tested the current version with a Visual Studio 2015 build and "NO_CACHING" (64 bit build) with Google Chrome on Windows 10 localhost, and was unable to reproduce the problem. Also fast reloading did not help.  #417 used Visual Studio 2015 on Windows 10, and I have it ready to run (in contrast to Qt5.5.1-mingw492), But reading #417 again, I found there the 32 bit version was used, so I will try the 32 bit version later, but it should not make any difference for small files.

Mail is just the user name (my 3 letters + 4 digits) at gmail dot com

**Comment by slidertom** [comment] 2017-03-13 20:58
same issue: 
Visual Studio 2015, win7 x64, CivetWeb 32 bits build.
GET http://127.0.0.1:8081/jquery-ui/jquery.tablesorter.js?ver=1 net::ERR_CONTENT_LENGTH_MISMATCH
GET http://127.0.0.1:8081/jquery/jquery-2.1.4.js?ver=1 net::ERR_CONTENT_LENGTH_MISMATCH
Reproducible only with Chromium based browsers, FF looks like to be ok.

**Comment by slidertom** [comment] 2017-03-13 23:13
if the difference 32 and 64 bits maybe:
uint64_t size;
cl = (int64_t)filep->stat.size;
         ^^^^^^^^^^^^
as:
typedef long long          int64_t;
typedef unsigned long long uint64_t

**Comment by bel2125** [comment] 2017-03-14 20:44
Hard to say what the difference really is, until I can reproduce it.
But since filep->stat.size is small (some kB), it should perfectly fit into a positive signed int32, so I cannot imagine any signed/unsigned 32/64 bit conversion problems.

**Comment by slidertom** [comment] 2017-03-14 21:28
handle_static_file_request
I do receive such values:
r1	16384	__int64
r2	16384	__int64
cl	34192	__int64
n       2
r1 and r2 are equal, is it correct? 
(looks like browser does not request any info..)

after:
cl = (n == 2) ? (((r2 > cl) ? cl : r2) - r1 + 1) : (cl - r1);
cl = 1;

**Comment by slidertom** [comment] 2017-03-14 21:34
(If it's required I can try to prepare a sample app. Please write.)

**Comment by bel2125** [comment] 2017-03-14 22:13
So there is a range header like "Range: bytes=16384-16384" (https://en.wikipedia.org/wiki/List_of_HTTP_header_fields, https://tools.ietf.org/html/rfc7233#section-3.1)

```C
hdr = mg_get_header(conn, "Range");
... (n = parse_range_header(hdr, &r1, &r2)) ...
```
with
```C
static int
parse_range_header(const char *header, int64_t *a, int64_t *b)
{
	return sscanf(header, "bytes=%" INT64_FMT "-%" INT64_FMT, a, b);
}
```

n=2 means both, upper and lower limit were read correctly
If they are the same, the client requests just one byte.
What is `filep->stat.size` in your case?  34192 corresponding to cl before cl = (n == 2) ? ...
Then there should be a reply
```
Content-Range: bytes 16384-16384/34192
```
And one byte of content.

This does not look very reasonable. Could you verify what HTTP request and response headers you get? Is there a Range and Content-Range header with the above values?

**Comment by grunk** [comment] 2017-04-04 08:53
I have the same problem too.
It's seems to happen with chromium based browser and IE. It's working fine (whatever is the browser) if civet is running on linux.

I attach some wireshark export showing the problem on windows and the exact same request done on the exact same server but running on linux and working.

Hope it can help.
[wireshark_civet.zip](https://github.com/civetweb/civetweb/files/892482/wireshark_civet.zip)
you can use "http" filter if needed.

I was not able to reproduce the problem on windows 10 on localhost. But querying from an other computer trigger the error ...

**Comment by bel2125** [comment] 2017-04-04 20:14
Thank you for the data. I checked `civet_export_win_ko.pcapng` - it has 25 packages and 11 TCP streams. Do you know which one problematic one is - I will also find it, if you could tell me what request went wrong.

GET / HTTP/1.1 (TCP stream 0, packages 1, 2, 3, 4) seems to be complete with 1405 bytes

GET /assets/css/loading.css HTTP/1.1 (TCP stream 2, packages 6, 11, 12, 17, 18) seems to be complete with 2937 bytes

GET /assets/css/custom.css HTTP/1.1 (TCP stream 3, package 7, 15,16) seems to be complete with 240 bytes

GET /styles.d41d8cd98f00b204e980.bundle.css HTTP/1.1 (TCP stream 4, packages 8, 13, 14) has 0 bytes

GET /inline.744212e2a0acc44e441e.bundle.js HTTP/1.1 (TCP stream 7, Package 19, 23,24,25) seems complete with 1460 bytes,

TCP streams 1, 5, 6, 8, 9, 10 are unanswered in the log - maybe the answer is sent later

So for all complete requests, the Content-Length response corresponds to the actual length in the reassembled TCP stream. I did not find a "Range" request header either.
Did I look at the right place?

**Comment by grunk** [comment] 2017-04-04 20:48
On my web app it's always the css from bootstrap which seems to start the problem : 

GET /assets/css/bootstrap.min.css HTTP/1.1 

In my dump it's not answered (answer never came) and it give me the net::ERR_CONTENT_LENGTH_MISMATCH on chrome. 
It's the first "big" static file civetweb has to serve but it also fail on other js file later in my html page.

I spent the all day trying to understand what's going on without success 🙄 
I checked the size sent inside the [header](https://github.com/civetweb/civetweb/blob/master/src/civetweb.c#L8050) and it's always correct.

I'll try tomorrow (gmt+2) to give you an html sample that failed every time when queried from a remote client.

**Comment by bel2125** [comment] 2017-04-04 22:27
So it's the first large file you download. Are the other files working?
GET /assets/css/bootstrap.min.css HTTP/1.1 is TCP stream 1 (numbered by WireShark in this log)
GET /assets/js/jquery-3.1.0.min.js HTTP/1.1 is TCP stream 5
GET /assets/js/bootstrap.min.js HTTP/1.1 is TCP stream 6
GET /polyfills.b339fe1c9053e0430748.bundle.js HTTP/1.1 is TCP stream 8
GET /vendor.f532a0f20d38e2059e9e.bundle.js HTTP/1.1 is TCP stream 9
GET /main.e18081342c732f8f303b.bundle.js HTTP/1.1 is TCP stream 10

What's the size of these files?

"Range" is sent by the client, if it only wants to read a certain part (range) of the file. The server will respond with a "206 Partial Content" and some "Content-Range" header.

**Comment by webxer** [comment] 2017-04-04 23:19
I am experiencing the similiar problem with a GWT web app.  I tried it in Chrome with the 32 bit and 64 bit CivetWeb.  I compiled both with Visual Studio 2017, but don't know if the NO_CACHE flag was enabled.
Attached is the web app if anyone is interested.  It's only serving three files html and two javascript files.
[ProVSimulator.zip](https://github.com/civetweb/civetweb/files/894768/ProVSimulator.zip)

**Comment by grunk** [comment] 2017-04-05 06:52
>So it's the first large file you download. Are the other files working?

The very small one (under 100k) usually works fine , but other bigger file fail. That's why i was thinking of filesize problem , but it's maybe just a coincidence

> What's the size of these files?

Css are around 100k but i have one js file which is around 1.5MB (350KB gziped).

I tried webxer sample and it show the problem too , but not every time. it took me few refresh to get it to crash.

The sample below show the problem every time (in my case at least). I added a screenshot of chrome and wireshark dump if it can be of any help.
It works in localhost (win10) , but not from an other remote windows client. My civetweb is embedded in a software compiled in 64bit with VS2015.
If the same sample app is hosted under linux , it works whatever the client is.

[sample.zip](https://github.com/civetweb/civetweb/files/895339/sample.zip)

**Comment by webxer** [comment] 2017-04-05 18:46
The previous web app I uploaded had smaller files, but a larger web app sample I have, like grunk's,  has a lot of trouble on Chrome with the larger files.   I also have problems with this web app on Firefox as well.   

I'm using the 64 bit version of Civetweb compiled with Visual Studio 2017.  I am on a Windows 7 64 bit machine, using Version 57.0.2987.133 (64-bit) of Google Chrome.

I have attached my larger GWT web app that is using a modified version of GWTBootstrap3 demo for tabs.  This has only been compiled for Firefox and the Chrome/Safari variant.

I also attached a sequence of screen captures that chronicle in Chrome, with the Developer tool output, the initial load and the subsequent 6 reloads
[webapp_sample.zip](https://github.com/civetweb/civetweb/files/900469/webapp_sample.zip)

**Comment by bel2125** [comment] 2017-04-05 19:24
Thank you for the example. I just tried to reload 02CAF43BC635527FCF6E5C93B06B4A17.cache.js several times, but the problem did not occur - I used a Windows 32 server (not Windows 64 - I would need a different system setup for this).

Is it possible at all to reproduce this with an isolated file, or only by loading an entire web page with several resources (images, css, ...)?

**Comment by bel2125** [comment] 2017-04-05 19:29
A google search for net::ERR_CONTENT_LENGTH_MISMATCH actually returns several possible reasons, some related to the server, some related to proxy settings, some to caches, some to scripts, ...
I'm not sure if all issues reported here have the same cause ...

**Comment by bel2125** [comment] 2017-04-05 19:47
I tried with curl, and found sometimes the connection is closed before all data is read:
`curl -i http://192.168.0.14:8080/vortekprovpoe/02CAF43BC635527FCF6E5C93B06B4A17.cache.js`
......curl: (18) transfer closed with 126643 bytes remaining to read

Maybe this could be the first somehow reproducible hint to this issue - I will have a look.

**Comment by bel2125** [comment] 2017-04-05 19:55
This might be related to a bug in line 4833, function `push`:
Replace
```} while ((timeout <= 0) || ((start - now) <= timeout_ns));```
by
```} while ((timeout <= 0) || ((now - start) <= timeout_ns));```
then the curl test works.

**Comment by webxer** [comment] 2017-04-05 20:07
bel2125 I just compiled the 64 bit Debug version I have with the fix and It works!!

Good job

**Comment by bel2125** [comment] 2017-04-05 20:11
Thanks for giving the decisive hints. And thanks everybody for your samples and wireshark logs. I will add you to the credits file.

Everybody: Please repeat your tests, so we can be sure I did not miss something.

**Comment by grunk** [comment] 2017-04-06 06:15
Fixed it for me too !
Great job

**Comment by bel2125** [comment] 2017-04-30 19:42
Fixed some weeks ago.
Closing this issue.

**Closed by bel2125** 2017-04-30 19:42 UTC
Labels: Status: done - waiting for submitter to confirm
