### ISSUE TITLE
clang static analyzer reports two issues on Linux for the library

### ISSUE THREAD

**Issue by chaudron** [civetweb/civetweb#794] opened 2019-10-10 11:47 UTC
See below how it was ran and the output:
```
$ scan-build make lib
scan-build: Using '/usr/bin/clang-8' for static analysis
/usr/bin/../libexec/ccc-analyzer -c -Wall -Wextra -Wshadow -Wformat-security -Winit-self -Wmissing-prototypes -DLINUX -Iinclude  -DUSE_STACK_SIZE=102400 -O2 -DNDEBUG -fPIC -fPIC src/civetweb.c -o out/src/civetweb.o
src/civetweb.c:12022:18: warning: Branch condition evaluates to a garbage value
        for (i = j = 0; href[i]; j++) {
                        ^~~~~~~
src/civetweb.c:18100:29: warning: 1st function call argument is an uninitialized value
        } else if (!check_acl(ctx, ntohl(*(uint32_t *)&so.rsa.sin.sin_addr))) {
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/netinet/in.h:401:21: note: expanded from macro 'ntohl'
#   define ntohl(x)     __bswap_32 (x)
                        ^~~~~~~~~~~~~~
2 warnings generated.
ar cq libcivetweb.a out/src/civetweb.o
scan-build: 2 bugs found.
scan-build: Run 'scan-view /tmp/scan-build-2019-10-10-134343-5157-1' to examine bug reports.
```

**Comment by bel2125** [comment] 2019-10-11 23:13
I don't think `href[i]` is a garbage value, since it is set in the ` mg_url_encode(uri, href, href_size);` call some lines before. That's probably a false positive.

And `so.rsa.sin` is initialized in `so.sock = accept(listener->sock, &so.rsa.sa, &len))`, since `so.rsa` is a union (socket programming uses several "weak" types).

**Comment by xtne6f** [comment] 2020-05-27 16:31
I think the first warning is caused by scan-build's lack of understanding of `strncmp()`. One of the solutions is modifying the `if` statement like this:
```diff
        for (i = j = 0; href[i]; j++) {
-               if (!strncmp(href + i, "%2f", 3)) {
+               if ((href[i] == '%') && (href[i + 1] == '2') && (href[i + 2] == 'f')) {
                        href[j] = '/';
```
I can't judge which is better for readability.

The second warning would be caused by scan-build's lack of understanding of `accept()`, still I recommend zerofill for `so.rsa` ( `memset(&so.rsa, 0, sizeof(so.rsa));` ). Because static analysis tools can not assume the protocol family of socket. ( Needless to say, `accept()` initializes the second parameter depending on the protocol family. )

**Comment by bel2125** [comment] 2020-05-27 21:20
> ... still I recommend zerofill for so.rsa ...

Done that for the entire "so" structure.

"strncmp" is used several times in the code, I think I will keep this.

**Comment by bel2125** [comment] 2021-11-21 15:35
Already fixed with https://github.com/civetweb/civetweb/commit/3550ccaa12d5b8c39a36997f78b4b474b4f8e510

**Closed by bel2125** 2021-11-21 15:35 UTC
