### ISSUE TITLE
Compiler errors on macOS with Xcode 9.0 beta 5

### ISSUE THREAD

**Issue by eyeplum** [civetweb/civetweb#503] opened 2017-08-14 08:18 UTC
When try to compile a project depends on civetweb with the clang embedded in Xcode 9.0 beta 5 on macOS, there are 2 new compiler errors:

```
/s2client-api/contrib/civetweb/src/civetweb.c:141:34: error: unknown warning group '-Wno-reserved-id-macro', ignored [-Werror,-Wunknown-warning-option]
#pragma clang diagnostic ignored "-Wno-reserved-id-macro"
                                 ^
/s2client-api/contrib/civetweb/src/civetweb.c:142:34: error: unknown warning group '-Wno-keyword-macro', ignored [-Werror,-Wunknown-warning-option]
#pragma clang diagnostic ignored "-Wno-keyword-macro"
                                 ^
```

These two errors were appearing as warnings when compiled with previous versions of the Xcode embedded clang.

As we have investigated in Blizzard/s2client-api#49, the errors are caused by two factors:

1. We are suppressing two warnings which doesn't exist any more [here](https://github.com/civetweb/civetweb/blob/master/src/civetweb.c#L188)
2. A CMake configuration is adding the `-pedantic-errors` flag [here](https://github.com/civetweb/civetweb/blob/master/CMakeLists.txt#L286)

Maybe we can remove those two `#pragma`s since those warnings are not there anymore?

**Comment by bel2125** [comment] 2017-08-14 19:02
I tried to get rid of the same warnings in the unit test yesterday (https://github.com/civetweb/civetweb/commit/99a76ac968f954604b651478321e8758160f67d1), but it seems to depend on compiler versions.
I'm already looking into this.

Do you have any idea when this warning disappeared - what version?

**Comment by eyeplum** [comment] 2017-08-15 07:56
Both on Xcode 8 and Xcode 9 the compilers are saying they are `unknown warning group`.

I don't have Xcode 7 at hand, but I guess the warning flags should be there, because that's the version we added those flags.

**Comment by bel2125** [comment] 2017-08-15 11:38
The problem is, I don't have any Xcode at hand right now, the tests run either on Travis or are done by contributors.

If this was required up to Xcode 7, a possible fix would be to check the clang version - I found [here](https://opensource.apple.com/source/clang/clang-800.0.38/src/configure.auto.html) this would be 3.9 for Xcode 8, released [September 2016](http://releases.llvm.org/). So the following check could work, but I can't test it
```C
#if (__clang_major__ < 3) || ((__clang_major__ < 4) && (__clang_minor__ < 9))
```
Could you try if this helps?

The alternative, to completely drop it might cause warnings on Travis CI - I have to check it there.

By the way: It's possible to build without "warnings as errors" even with the current CMakeFile by setting `CIVETWEB_ALLOW_WARNINGS`. It's disabled by default, so Travis CI and AppVeyor build without warnings for selected compilers - currently mainly selected by Travis and AppVeyor. It seems not possible to build warning free for every compiler and every compiler version. Warning free on selected versions of selected compilers (and selected static source analysers) seems to be best in reach anyway.

**Comment by eyeplum** [comment] 2017-08-15 11:49
I have modified those lines to the following:

```
#ifdef __clang__
#if (__clang_major__ < 3) || ((__clang_major__ < 4) && (__clang_minor__ < 9))
/* Avoid warnings for Xopen 7.00 and higher */
#pragma clang diagnostic ignored "-Wno-reserved-id-macro"
#pragma clang diagnostic ignored "-Wno-keyword-macro"
#endif
#endif
```

And it's building (tested with Xcode 8 and Xcode 9).

**Comment by bel2125** [comment] 2017-08-15 11:53
It seems this error came with Xcode 7 and is gone again with Xcode 8, so it could be something like
```
if (__clang_major__ == 3) && ((__clang_minor__ == 7) || (__clang_minor__ == 8))
/* Avoid warnings for Xcode 7. It seems it does no longer exist in Xcode 8 */
#pragma clang diagnostic ignored "-Wno-reserved-id-macro"
#pragma clang diagnostic ignored "-Wno-keyword-macro"
#endif
#endif
``` 
Also Travis CI seems to like it this way.

**Comment by eyeplum** [comment] 2017-08-15 11:59
True, I tried this and it's also working.

**Comment by bel2125** [comment] 2017-08-15 13:41
Ok, so it's fixed. Then let's close this issue.

**Closed by bel2125** 2017-08-15 13:41 UTC
