### ISSUE TITLE
Add ECDH support for SSL handshake

### ISSUE THREAD

**Issue by mewalig** [civetweb/civetweb#249] opened 2016-01-26 03:43 UTC
I think this is as simple as e.g. adding 
```SSL_CTX_set_ecdh_auto(s, 1);```

to ```sslize()``` just before ```SSL_new()```

That change will allow civetweb, in conjunction with a sufficiently updated SSL library, to support https without a Chrome (and probably other browsers) showing, when you click on the SSL lock -> Connection, that "Your connection to xxx.com is encrypted using an obsolete cipher suite"

**Comment by bel2125** [comment] 2016-01-26 20:11
Did you set `ssl_cipher_list` and `ssl_protocol_version` ?
(see https://github.com/civetweb/civetweb/blob/master/docs/UserManual.md)

I do not get a warning with FireFox. I have not checked with Edge and Chrome (they are installed at another PC - I can check this later).
What cipher suites are considered as obsolete by Chrome?

**Comment by mewalig** [comment] 2016-01-26 20:41
If you look at two sites, one that uses RSA and one that uses ECDH_RSA for the key exchange, Firefox does not seem to differentiate but Chrome does (rightly so, as far as I know). It would be better to have at least some way to tell civetweb to use ECDH_RSA, if not have it do that as default behavior. 

As an aside, one might make the same observation / arguments that I make here for ECDH_RSA about DHE_RSA.

I see ssl_cipher_list and ssl_protocol_version, but as far as I can tell, the above issue still exists, because even if ECDH_RSA is supported and available, the SSL api will choose RSA unless there is an explicit ECDH-related call first, such as SSL_CTX_set_ecdh_auto() (not sure why they wouldn't make the API just do this automatically if it's considered better than RSA, but out of my jurisdiction).

Here are some screenshots from my Chrome connections on the two sites:

![image](https://cloud.githubusercontent.com/assets/8260442/12593710/6c437012-c440-11e5-8abd-33c80dbff854.png)

![image](https://cloud.githubusercontent.com/assets/8260442/12593732/8a7e94f8-c440-11e5-895e-b8a5f0d69f70.png)

**Comment by bel2125** [comment] 2016-01-26 21:30
> Here are some screenshots from my Chrome connections on the two sites:
> ...
> ... two screenshots ...
> ...

This is the result of adding / not adding `SSL_CTX_set_ecdh_auto()` to civetweb?

**Comment by mewalig** [comment] 2016-01-26 21:40
The one that says "obsolete cipher suite" (the first one) is from not adding ```SSL_CTX_set_ecdh_auto()```. The one that says "modern cipher suite" is from adding ```SSL_CTX_set_ecdh_auto()```

**Comment by bel2125** [comment] 2016-01-26 21:45
Since civetweb binds OpenSSL dynamically, one would have to redefine `SSL_CTX_set_ecdh_auto` (with the other defines, e.g. `SSL_CTX_clear_options`).

```
#define SSL_CTX_set_ecdh_auto(ctx, onoff) \
        SSL_CTX_ctrl(ctx,SSL_CTRL_SET_ECDH_AUTO,onoff,NULL)
```
and append the SET_ECDH_AUTO option to the other options:
```
#define SSL_CTRL_OPTIONS (32)
#define SSL_CTRL_CLEAR_OPTIONS (77)
#define SSL_CTRL_SET_ECDH_AUTO (94)
```
In case the openssl library is too old, option 94 will probably do nothing, so this should not be a problem.

What incompatibilities may be caused by adding this option?

**Comment by bel2125** [comment] 2016-02-14 19:25
`SSL_CTX_set_ecdh_auto(ctx->ssl_ctx, 1);` is set.
Could you repeat your test with the current version?

**Comment by bel2125** [comment] 2016-04-25 18:54
I am not aware of any remaining problems, so I'm going to close this issue.

**Closed by bel2125** 2016-04-25 18:54 UTC
Labels: Status: done - waiting for submitter to confirm
