### ISSUE TITLE
Question: how do I enable lua error notification/logging?

### ISSUE THREAD

**Issue by danielrempel** [civetweb/civetweb#231] opened 2015-11-28 08:12 UTC
Is there any way to enable writing lua execution errors?

**Comment by bel2125** [comment] 2015-11-28 22:10
Are you using Lua scripts (*.lua) or Lua lages (*.lp)?

In both cases, you get some response in the browser:

[bad_script](https://github.com/civetweb/civetweb/blob/master/test/bad_script.lua)

```
r:\/bad_script.lua:2: syntax error near <eof>
...
```

[bad_page](https://github.com/civetweb/civetweb/blob/master/test/bad_page.lp)

```
test 
Lua error:
r:\/bad_page.lp+1:1: syntax error near <eof>
...
```

**Comment by bel2125** [comment] 2016-01-06 17:23
Make sure, you passed the `error_log_file` option when you start the server - either as a command line option or in the `civetweb.conf` file. If you are using the Windows stand-alone server, you can enter this option in the GUI.

In general, Lua scripts (`*.lua`) log some more errors than Lua server pages (`*.lsp`).

You could also write explicitly to the error log using the `mg.cry(some_message)` function in Lua.

If you need more help, I would need some information on your system - which operating system are you using, are you using `*.lua` or `*.lsp`, do you want to log errors detected by your Lua scripts (e.g. invalid requests) or find errors in the Lua scripts (e.g. syntax errors in your scripts), ...

**Comment by bel2125** [comment] 2016-05-13 22:16
Since there are no further questions, I suppose the answers above helped, or the problem is no longer relevant.
I'm going to close this issue - in case there are still problems, please open a new one, or create a thread in the civetweb discussion group (https://groups.google.com/d/forum/civetweb).

**Closed by bel2125** 2016-05-13 22:16 UTC
Labels: question, Status: waiting for info from submitter
