### ISSUE TITLE
Deprecated mg_set_user_connection_data() used in embedded_c example

### ISSUE THREAD

**Issue by c-mauderer** [civetweb/civetweb#924] opened 2020-10-08 12:53 UTC
Hello,

the embedded_c example uses the deprecated mg_set_user_connection_data() function [here](https://github.com/civetweb/civetweb/blob/a5941ebf1e571ab07007c9779c45f99be66dc8cb/examples/embedded_c/embedded_c.c#L792) Issue #452 tells that the examples are using a new API. Did I miss something?

Best regards

Christian

**Comment by bel2125** [comment] 2020-10-08 21:03
> Issue #452 tells that the examples are using a new API

I did not find this statement there ... but I agree that it makes sense to avoid deprecated interfaces in the C example.

An example for the new API is here: https://github.com/civetweb/civetweb/issues/744 ... after creating the new interface, the documentation was missing and has been added with #744 

The only "problem" with mg_set_user_connection_data is, it requires a const cast in various situations. This could be fixed by removing the "const" from all `mg_connection *` in civetweb.h ... however, the `const` is useful to show in what callbacks you may call the `mg_read`/`mg_write` functions and where you have to avoid them.

**Comment by c-mauderer** [comment] 2020-10-09 07:06
> > Issue #452 tells that the examples are using a new API
> 
> I did not find this statement there ... but I agree that it makes sense to avoid deprecated interfaces in the C example.
> 

The last comment tells that _"The current release has interfaces that can be used to avoid const_casts (see comments above and code in the example directory)."_

I thought that means that there should be code that demonstrates it. But it's not really that relevant whether I misunderstood or whether the comment has been misleading. What's relevant is that an example would be nice ;-)

> An example for the new API is here: #744 ... after creating the new interface, the documentation was missing and has been added with #744

Thanks. I'll take a more detailed look at that. Also I have to say that the function seems a bit difficult. If I understand it correctly, it is called for every connection (and not only websockets). That means that I can for example use `malloc()` to allocate some memory for handling stuff during the websocket connection. But if the connection is no websocket, that memory is just unused till the connection is closed. If I have a website with some images, that means that a normal browser will cause a lot of useless malloc and free calls. Not really nice for an embedded system that might have to fight with small memory or heap fragmentation. Also it opens a door for DoS attacks.

> 
> The only "problem" with mg_set_user_connection_data is, it requires a const cast in various situations. This could be fixed by removing the "const" from all `mg_connection *` in civetweb.h ... however, the `const` is useful to show in what callbacks you may call the `mg_read`/`mg_write` functions and where you have to avoid them.

Removing a const with a cast can be sometimes problematic on embedded systems. If a variable is const, the compiler can put it in a read only memory like flash. In that case removing const can be fatal. I assume that the connections are created dynamically in RAM in case of civetweb so it most likely works without problems in this case. But I'm just a bit wary of these kind of casts. Beneath that it causes a compiler warning when compiled with `-Wcast-qual`

**Comment by bel2125** [comment] 2020-10-09 20:14
First, let's repeat what CivetWeb uses this "const" for, since it's probably not what "const" was intended for in the C/C++. There are some callbacks that use a "const struct mg_connection * input" and some use the same without const. It the input is a const pointer, you must not read/write from this connection (mg_read, mg_write, mg_printf, mg_send...). If the input pointer is not const, you can use all read/write functions.

I think there are some possible options to deal with the current situation:

1) Use the mg_set_ API, that might require a const-cast in some situations.

Advantage: This API is simple, available since many years and has no "real" issues (exceptions, memory leaks, ...). You may just use that const cast, completely unexited, and everything just works fine.

Disadvantage: It requires a const cast - that might be considered as "ugly"

I understand the problem you mentioned with const casts on embedded systems, and I am sure you are not affected in this specific use case. The underlying object has been allocated using malloc, and just set cast to const just before calling the callback that is not supposed to call mg_read.

2) Use the new API to initialize every thread once. After initialization, the pointer is a read only, but you can use a pointer to a pointer if you want to do modifications.

Advantage: No const cast required. Works for different thread and connection types. Allows to implement usecases not possible with mg_set_
Disadvantage: More complicate to use

I don't think you will have DoS or OOM problems, if you do it right. If you only allocate something like a pointer to struct { whatIsit: someEnum; moreData: somePointer;}, you don't waste much memory, and you can still modify "modeData" if you like.

3) Remove all the "const" from the civetweb.h API.

Advantage: "const" was not used here in the same way "const" is typically used in C and in the way "const" was intended to be used. All issues with "const casts" are gone immediately (this issue and a lot of others you may find as "const in C/C++ is a source of constant problems", "why const sucks", ...). 

Disadvantage: Currently const is an indicator if you are allowed to use mg_read/mg_write in a callback or not. If it is removed, everyone has to check this in the documentation only. If you do it wrong, the connection might go into an "unusable" state (effectively, the behavior is undefined).


4) Replace the API: Do not use "struct mg_connection *" and "const struct mg_connection *", but "struct mg_readwriteable_connection *" and "struct mg_not_readwritable_connection *". This would be clean, but completely incompatible. Therefore one would need to keep the existing API for compatibility reasons for a long time anyway. I don't want to add yet another option to do the same.



Effectively the "just use a const cast" option (1) does not appear that bad after all - I tend I will "un-deprecate" it.

And if you don't like it, use option (2). I can add an example for option 2, but it is and will always be "a bit difficult" as compared to option (1).

**Comment by bel2125** [comment] 2020-10-10 16:48
I missed the obvious alternative: Adding the `const` to `mg_set_user_connection_data`. It does not perform any read/write operation.

**Comment by c-mauderer** [comment] 2020-10-12 06:48
> First, let's repeat what CivetWeb uses this "const" for, since it's probably not what "const" was intended for in the C/C++. There are some callbacks that use a "const struct mg_connection * input" and some use the same without const. It the input is a const pointer, you must not read/write from this connection (mg_read, mg_write, mg_printf, mg_send...). If the input pointer is not const, you can use all read/write functions.

That's a bit of an odd usage of const. But it's established in this software so I won't start a discussion regarding that. I'm nearly sure that I missed it: Is that document somewhere?

> Effectively the "just use a const cast" option (1) does not appear that bad after all - I tend I will "un-deprecate" it.
>
> And if you don't like it, use option (2). I can add an example for option 2, but it is and will always be "a bit difficult" as compared to option (1).

The API from (1) is really quite simple to use compared to the one from (2). If you plan to un-deprecate it: Maybe you could add a note to the documentation that the const cast is OK?

> I missed the obvious alternative: Adding the const to mg_set_user_connection_data. It does not perform any read/write operation.

That sounds like a good solution too from a user perspective.

**Comment by bel2125** [comment] 2021-02-19 13:13
>>    I missed the obvious alternative: Adding the const to mg_set_user_connection_data. It does not perform any read/write operation.

> That sounds like a good solution too from a user perspective.

I already implemented this option some months ago: https://github.com/civetweb/civetweb/commit/68c0a7c37246c7edbb2d148ca834c82d572b2be0

Thus, I think this issue can be closed.

**Closed by bel2125** 2021-02-19 13:13 UTC

**Comment by c-mauderer** [comment] 2021-02-19 18:04
Thanks. I missed that it is implemented. Otherwise I would have closed it myself.
