### ISSUE TITLE
Using it as server and close a websocket connection will crash

### ISSUE THREAD

**Issue by Gitzzq** [civetweb/civetweb#515] opened 2017-09-08 22:55 UTC
1. Run Civetweb as a server and accept a **websocket** client, with **SSL enabled**.
2. In another thread call mg_close_connection(conn) to close the client's connection (e.g. close a timeout connection in a timer thread)
3. It will crash at line 5671 in pull_inner(...)
line 5667:    if (conn->ctx->stop_flag) {
line 5668:	      return -2;
line 5669:	   }
line 5670:	   if (pollres > 0) {
line 5671:	   nread = SSL_read(conn->ssl, buf, len);    //conn->ssl == NULL and then cause exception

I tried to move "conn->ctx->stop_flag = 1;" in mg_close_connection(conn) to above "if (conn->ctx->context_type == 2) {" :

	/* both server and client context: loops must end */
	conn->ctx->stop_flag = 1;
	if (conn->ctx->context_type == 2) {
		unsigned int i;

and it worked for me.

**Comment by bel2125** [comment] 2017-09-09 07:44
What commit number is the code you are referring to?

In the current head, d132047971dae0b1830a686b891974088c3e27ca, the line `/* both server and client context: loops must end */` in `mg_close_connection` is split in a server and a client part:
https://github.com/civetweb/civetweb/blob/d132047971dae0b1830a686b891974088c3e27ca/src/civetweb.c#L14705

What version did you use to test?

**Comment by zouzhiquan** [comment] 2017-09-11 18:26
Sorry I don't like Git client so I always download the whole zip instead of pull one file, so I don't have the Git commit number, but that was the latest version I downloaded on last Friday (09/08/2017).

Let's use commit number 14705 then basically I just moved
 `line 14706: conn->ctx->stop_flag = 1;`
 out from the **if block** to always set the stop flag.
`line 14699: if(conn->ctx->context_type == 2);`

**Comment by bel2125** [comment] 2017-09-11 19:59
So, your change basically calls `conn->ctx->stop_flag = 1;` for every value of `conn->ctx->context_type`, right?
If you do this for context type 1, you basically stop the entire server (similar to `mg_stop`).

But, this is probably not what you want?
As a server, you want to drop one websocket connection while still running other websocket and "normal" http(s) connections?

**Comment by zouzhiquan** [comment] 2017-09-11 20:37
You are right, of course I want the server still run and serve other connections......., I might overlook it and haven't done enough test.......

**Comment by bel2125** [comment] 2017-09-11 20:56
You have to leave the loop `while (!conn->ctx->stop_flag) {` in `read_websocket`, line 11151
There are some other ways to leave this loop than `conn->ctx->stop_flag`, like callback return values, ...

From what I understood about your requirements, probably you run into the line with this mark `/* TODO: retry condition */` for the connections you want to close. Could you check if this happens?
We could add a `break` condition there to exit the loop, but it will need some additional variable and some check in `mg_close_connection`

**Comment by zouzhiquan** [comment] 2017-09-11 22:21
I changed line 5708 and 5745 from

`if (conn->ctx->stop_flag) {`

to

`if (conn->ctx->stop_flag || conn->must_close == 1) {`

and tested ok.

**Comment by bel2125** [comment] 2017-09-12 18:06
I'm afraid changing this in `pull_inner` will cause problems when handling requests with larger body data (like POST/PUT requests to upload files from) in scripts (Lua/CGI), or when `keep_alive = no`

Did you run the Lua form handling test with some larger data?

**Comment by zouzhiquan** [comment] 2017-09-12 18:10
No, I don't have CGI/Lua environment to test.
Could you take a look my original crash case and provide a better fix?

**Comment by bel2125** [comment] 2017-09-12 18:22
Yes, I can take a look.

Currently I'm working on a V1.10 release, and that's somewhat problematic because of a Travis CI update that came at a very unpleasant moment, blocking the release (https://github.com/civetweb/civetweb/issues/512). We already have an release candidate, and some tests are running. 

Is it enough for you to get some draft to test on your own now, and I'll add the real fix a week or two later?

**Comment by zouzhiquan** [comment] 2017-09-12 18:24
Sure I can wait 1-2 weeks, appreciate it.

**Comment by bel2125** [comment] 2017-09-19 19:38
Since the V1.10 release is still somewhat delayed, I did not have time to set up a proper test environment. But I have an idea how it could be solved - unfortunately not tested.
In `read_websocket`, there is a condition:

```C
	/* Loop continuously, reading messages from the socket, invoking the
	 * callback, and waiting repeatedly until an error occurs. */
	while (!conn->ctx->stop_flag) {
```
could you try
```C
	/* Loop continuously, reading messages from the socket, invoking the
	 * callback, and waiting repeatedly until an error occurs. */
	while (!conn->ctx->stop_flag && !conn->must_close) {
```
It could take ~30 seconds (`websocket_timeout_ms`) until the connection is closed. If this delay is a problem, I need to add a new variable to the connection object.

**Comment by zouzhiquan** [comment] 2017-09-21 16:23
Just tried, but it didn't work. After the SSL has been closed and cleaned up the conn->ssl is NULL, and then causes access violation at line 5712
`nread = SSL_read(conn->ssl, buf, len);`
in pull_inner(...)

**Comment by bel2125** [comment] 2017-09-21 18:17
I think you have to set only `conn->must_close` without performing the rest of `close_connection`.
Integrated into `civetweb.c`, this is somewhat more to do:

[possible_patch.txt](https://github.com/civetweb/civetweb/files/1322312/possible_patch.txt)
[civetweb.c](https://github.com/civetweb/civetweb/files/1322314/civetweb.txt)

I still don't have a test case implemented, but only an idea how it needs to be done.

**Comment by zouzhiquan** [comment] 2017-09-21 18:40
I tested your fix but it didn't work.

Code snippet since line 5711:
`		pollres =
		    mg_poll(pfd, 1, (int)(timeout * 1000.0), &(conn->ctx->stop_flag));
		if (conn->ctx->stop_flag ) {
			return -2;
		}
		if (pollres > 0) {
			nread = SSL_read(conn->ssl, buf, len);`

The problem is because when the mg_poll(...) is returned due to the socket is closed AND the conn->ssl is destroyed and set to NULL, then "SSL_read(conn->ssl, buf, len)" will raise an access violation exception,  the flag you set for "while (!conn->ctx->stop_flag && !conn->must_close) " in read_websocket(...) is not triggered yet.

The SSL_read(...) must not be called after the conn->ssl is cleaned up.

**Comment by bel2125** [comment] 2017-09-21 18:43
Do you have some minimal test for this?

**Comment by bel2125** [comment] 2017-09-21 18:56
ok. I think I got the problem

**Comment by bel2125** [comment] 2017-09-21 19:17
[civetweb.c](https://github.com/civetweb/civetweb/files/1322467/civetweb.txt)

**Comment by zouzhiquan** [comment] 2017-09-21 19:42
I tested it, it didn't crash this time.
But I think it's too passive........, I set the websocket timeout option to 10 minutes then I waited 10 minutes to see the client's connection is closed.........

**Comment by bel2125** [comment] 2017-09-21 20:19
I would add websocket ping-pong every ~5 to ~30 seconds, and set the timeout no longer than 60 seconds, so you would not need to wait longer than the ping pong time.

Probably a 
`if (conn->ctx->stop_flag || (conn->in_websocket_handling && conn->must_close == 1)) {`
in the read function will make it quicker now, but there must be a more clear solution. Doing it with this complex stop condition this will cause maintenance problems on the long term.

**Comment by bel2125** [comment] 2017-09-21 20:31
Do you know the websocket ping-pong protocol? The server can send a special "ping" message to the client, and the client can send a "pong" back. If the client is a (modern) browser, it will do this automatically - see https://stackoverflow.com/questions/10585355/sending-websocket-ping-pong-frame-from-browser
Currently you can do ping/pong handling only from your callback, or from a Lua-Websocket script. It is on my list of possible features for V1.11, to add this to the server itself.

Then, server and client will send this ping/pong messages once every ~10 seconds, so the server can check if the client is still there. Then, closing a connection will work in 10 seconds as well.

**Comment by zouzhiquan** [comment] 2017-09-21 20:31
I do have a ping for every 30 seconds and timeout a client connection if no message for 90 seconds, and that's why I found the crash initially. The 10 minutes timeout is the old code just for some extreme cases like client side doesn't implement the ping/pong or whatever reason.

But for my application waiting for 30-60 seconds is not acceptable because of the requirement.........as there are some important logic depends on the close event (in handleClose() ).

BTW, there is a compile error with VS2010 at line 14206
`ssl_info_callback(const SSL *ssl, int what, int ret)`

the "const" is needed.

**Comment by bel2125** [comment] 2017-09-21 20:34
> BTW, there is a compile error with VS2010 at line 14206
> ssl_info_callback(const SSL *ssl, int what, int ret)
> the "const" is needed.

I once had that, and got a compile error somewhere else.
Is it an error or warning?

**Comment by zouzhiquan** [comment] 2017-09-21 20:39
It's an error. 
But never mind, only when I rename the extension name from .c to .cpp then it becomes an error. Using the original .c is fine.

**Comment by bel2125** [comment] 2017-09-21 20:52
Ok.

Still, closing the websocket server in ~1 second should be based on the new code. Maybe `mg_close_connection` should not set `conn->must_close` to 1, but a new flag `conn->stop_flag` (similar to the server stop flag, but only for one connection). This would be cleaner, much easier to maintain ... but more work to add it initially (too much work for today).

**Comment by bel2125** [comment] 2017-09-21 20:53
And I need to add a new unit test as well.

**Comment by bel2125** [comment] 2018-09-10 20:10
Websocket ping pong is part of the current release V1.11

**Closed by bel2125** 2018-09-10 20:10 UTC
