### ISSUE TITLE
<incomplete type> struct mg_context *ctx

### ISSUE THREAD

**Issue by DisjointTech** [civetweb/civetweb#354] opened 2016-09-05 03:24 UTC
The file embedded_c.c, in the examples directory--it compiles successfully, but display `-1 listening ports:` upon execution and just hangs there.
When I investigated the flow of execution with GDB; the command `ptype ctx` displayed `type = struct g_context { <incomplete type> } *`

**Comment by saumitravikram** [comment] 2016-09-05 11:25
Hi @DisjointTech, even i faced the same issue while trying to debug using gdb in eclispe.

The root cause of it was i was in debug_configurations the working directory was set to root directory of the project. I changed to include to the current directory where the executables of embedded_c were present.

The reason for it was ctx is not being initialized properly since it was failing to read SSL certificate,since in code relative path for it is specified from embedded_c location.
```
	const char *options[] = {"document_root",
	                         DOCUMENT_ROOT,
	                         "listening_ports",
	                         PORT,
	                         "request_timeout_ms",
	                         "10000",
	                         "error_log_file",
	                         "error.log",
#ifdef USE_WEBSOCKET
	                         "websocket_timeout_ms",
	                         "3600000",
#endif
#ifndef NO_SSL
	                         "ssl_certificate",
	                         "../../resources/cert/server.pem",
#endif
```

Hope this help.If not can you please provide in details of OS,compiler version,gdb version and IDE if any.

**Comment by bel2125** [comment] 2016-09-05 21:01
struct mg_context is intentionally an incomplete type outside civetweb.c
The pointer to this structure is basically a handle to the outside world, members are only used inside civetweb.c.

This does not explain the hang. Please send some system information (obtained with civetweb -I).
What command line did you use? A valid option would be `-listening ports 80` not `-1 listening ports:`.

**Comment by DisjointTech** [comment] 2016-09-06 01:03
Hello bel2125 , hello saumitravikram. 
Here is the output of civetweb -I:
```
CivetWeb V1.9
CivetWeb V1.9 - Linux #1 SMP Debian 4.6.4-1kali1 (2016-07-21) (4.6.0-kali1-amd64) - x86_64
Features: Files HTTPS CGI
Version: 1.9
Build: Sep  4 2016
gcc: 6.1.1
Data model: i:2/4/8/8, f:4/8/16, c:1/4, p:8, s:8, t:8
```

In the `Makefile`, I modified the CFLAGS to `CFLAGS = -Wall -O0 -g -DDEBUG_ENABLED -DSF_VISIBILITY -fvisibility=hidden -fno-strict-aliasing -I$(TOP)/include $(COPT) -DUSE_WEBSOCKET -DUSE_IPV6`  before recompiling it; yet I could not step into `mg_start`, therefore, I couldn't tell what was going on from beyond there. 

When debugging `civetweb`, I can print elements of `struct mg_context` when `mg_start` returns, on the contrary, when debugging `embedded_c`, I get "incomplete type" when I try to print any element of `struct mg_context`.

As saumitravikram mentioned above, I believe something is wrong with the `options`; but I haven't understood what `debug_configurations` is. I have tried a full path to SSL certificate and made sure the user running embedded_c has access to the file, but unfortunately it didn't work.

**Comment by bel2125** [comment] 2016-09-07 09:36
From my understanding "incomplete type" is exactly what I expect anywhere outside "civetweb.c".
It's actually a feature that "struct mg_context" is a structure inside civetweb.c, but only used as a pointer to something unknown outside - it could have been a void pointer outside civetweb.c, but a pointer to an incomplete struct allows for some compile time type checking. But it does not allow to see the members, and this is intentional.
If there is some way to see the members in another file than civetweb.c in the debugger, this is a bug or feature (depending on the point of view) of the debugger - the compiler does not see the members outside civetweb.c (so from my point of view the debugger does not need to see it either).

Your system seems to be a typical 64 bit Linux PC, similar to one of my test systems.

If you think, there is a problem with options, try to reduce them:
```C
const char *options[] = {"document_root",
	                         DOCUMENT_ROOT,  // <-- this is ".", ok

	                         "listening_ports",
	                         PORT, // <-- this is "8888r,8843s", try "8888"

	                         "request_timeout_ms", // <-- not required
	                         "10000",  // <-- not required

	                         "error_log_file",  // <-- not required, but useful
	                         "error.log",  // <-- not required, but useful

#ifdef USE_WEBSOCKET
	                         "websocket_timeout_ms",   // <-- not required, and not in your ifdef set
	                         "3600000",   // <-- not required, and not in your ifdef set
#endif

#ifndef NO_SSL
	                         "ssl_certificate",  // <-- can be removed when using port 8888 
	                         "../../resources/cert/server.pem",  // <-- can be removed when using port 8888 
#endif

0  // <-- indicates end of options list
};
```

**Comment by saumitravikram** [comment] 2016-09-07 17:40
You should try suggestion given by @bel2125 to reduce the options.
Seems like the issue is with the port number.There is a possibility some service is already port 8888.

I replicated the issue in my machine, by running 2 instances of embeded_c simultaneously .The second instance of embeded_c showed listening_port -1.

So try changing port number before changing any other options or removing options.

**Comment by DisjointTech** [comment] 2016-09-07 21:43
Thank you for your assistance.
It's now running after modifying the options to:
```
        const char *options[] = {"document_root",
                                 DOCUMENT_ROOT,
                                 "listening_ports",
                                 "8080r",
                                 "request_timeout_ms",
                                 "10000",
                                 "error_log_file",
                                 "error.log",

#ifdef USE_WEBSOCKET
                                 "websocket_timeout_ms",
                                 "3600000",
#endif
                                 0};
```

Modifying only the port number didn't do the trick, I also had to remove the "ssl_certificate" option.
In my case, embedded_c was not trying to use a port already in use.
I'd like to know the source of this issue; is it the ssl certificate?
Thank you in advance!

**Comment by saumitravikram** [comment] 2016-09-08 01:03
That's great.To find the root cause of the issue we need to see the logs in error.log since issue is not repo at our end.

Use same options as in code
```
const char *options[] = {"document_root",
                             DOCUMENT_ROOT,  // <-- this is ".", ok

                             "listening_ports",
                             PORT, // <-- this is "8888r,8843s"

                             "request_timeout_ms", 
                             "10000",  

                             "error_log_file",  // <-- make sure,error log option is present
                             "error.log",  // <-- make sure,error log option is present

#ifdef USE_WEBSOCKET
                             "websocket_timeout_ms", 
                             "3600000",   
#endif

#ifndef NO_SSL
                             "ssl_certificate",  
                             "../../resources/cert/server.pem",   
#endif

0  // <-- indicates end of options list
};
```
Compile and run with this and please paste the output of error.log file in here.It will help to debug in which initialization step failed in mg_start().We can take up more from there.

**Comment by DisjointTech** [comment] 2016-09-08 01:58
Here's the content of error.log after recompiling embedded_c with the default options as shown above:
`[1473298198] [error] [client ] load_dll: cannot load libcrypto.so`

I didn't have the libssl-dev package installed on my system. Installing libssl-dev and loading it with the `ldconfig` command fixed it. It's running just fine!

**Comment by bel2125** [comment] 2016-09-17 16:41
Anything else I can do to help?
If everything is working now, let's close this issue.

**Comment by bel2125** [comment] 2016-11-06 21:48
Solved ~2 month ago --> closing this issue.

**Closed by bel2125** 2016-11-06 21:48 UTC

**Comment by DisjointTech** [comment] 2016-11-09 04:06
I apologize for the delay!
Yes, it working.
