### ISSUE TITLE
Linger options 

### ISSUE THREAD

**Issue by jd-boyd** [civetweb/civetweb#288] opened 2016-03-30 20:37 UTC
In `close_socket_gracefully`, `linger` is set to 1 second.

I notice that in nginx, haproxy, and varnish, either linger is 0 seconds or not set based on admin configuration.  Apache doesn't set it ever, same as lighttpd.

It seems to me that civetweb should consider moving to making this configurable instead of hard coding it to 1 sec.

I propose adding a `linger_seconds` option for the option array passed to `mg_start()`.  If not set, then SO_LINGER wouldn't be set.  If set, then its value would be used for l_linger value in the linger struct.

If this shouldn't change, perhaps we could get documentation for why civetweb differs in this detail from other web servers (currently it explains what it does, but not why it differs from other servers).

**Comment by bel2125** [comment] 2016-03-30 21:36
Do you think there is any problem with setting it to one second?

**Comment by jd-boyd** [comment] 2016-04-01 20:31
I'm not sure.  I think it should be fine, however I don't see a point.  1 second is long enough that it should be hard to DDOS a civetweb server, and yet if we aren't worried about that, it won't be as reliable as no linger.

I was looking at this because of connection issues I'm having, but I decided it wasn't related to the linger after all, but it still stands out as an odd choice.

It could certainly be left alone, but I think it would make sense to make it an option and put the default back to the normal close behavior.

**Comment by bel2125** [comment] 2016-04-02 00:18
There are different ways to approach this topic.

The first approach: 
---
If there is no problem, do not fix it.

The second approach: 
---
Think about the code in detail. Is it meaningful to set it to one second?
Probably yes - you already stated a DDOS would be hard.
Is an configurable option required?
Only if there would be a reason to choose a different value, and if there are guidelines how to set this value - otherwise it's just an opportunity to get a bad server because of a bad configuration by the user.

The third approach:
---
You asked for reasons why it is set to one second, while others set it to 0 or don`t set it.

So, why is there a linger set to one second:

This part of the code is older than CivetWeb.
As you probably know, CivetWeb was forked from mongoose.
There is a project that forked the last MIT version of mongoose, and kept that state for archiving purposes: https://github.com/pfalcon-mirrors/mongoose-mit
The "linger one second" is already set, before CivetWeb existed:
https://github.com/pfalcon-mirrors/mongoose-mit/blame/master/mongoose.c#L4905

Some time ago, mongoose was hosted at google code and using mercurial source control (not github and git), it did not have any "linger" setting:
https://bel2125-mongoose.googlecode.com/hg-history/2.10/mongoose.c

However, the socket shutdown logic was broken. You might find some of this discussion when you search for "Mongoose + QtWebView", "missing contents on qt/webkit based browsers", "Errors when issuing multiple POST request simultaneous", ... I think some of the historical information is lost since google code was closed (at least I can not find it anymore - I just saved the code some time ago, e.g., the [100 images test](https://github.com/civetweb/civetweb/blob/master/test/100images.htm)).

In fact I created my (no longer maintained) mongoose fork before the introduction of "linger" since some important fixes never got merged into the mainline. In particular the socket shutdown logic had some problems. If you are interested in the work done on the shutdown that time, you need to study what GerHobbelt did - I think he moved his repository to GitHub: https://github.com/GerHobbelt/civet-webserver
The shutdown logic in his code looks different:
https://github.com/GerHobbelt/civet-webserver/blob/master/mongoose.c#L6870
https://github.com/GerHobbelt/civet-webserver/blob/master/mongoose.c#L7558

Neither his nor my fixes from that time got merged into the mainline. 
Instead someone else introduced the "linger for one second" logic, which also affects the shutdown behavior. I was not following the discussion anymore, since I already solved this problem differently, so I can not tell you the exact reason.

The civetweb code passes my original test from that time.
Changing the shutdown logic is several weeks of work - I know that from previous experience.
That's why I don't want to start this if there is no compelling reason.
I might check if some of the code from GerHobbelt should me merged into civetweb - but certainly not before the next release.

**Comment by jd-boyd** [comment] 2016-04-02 05:26
Thank you for all the reading material. I will be going through it carefully.

Interestingly, the problems I was perusing that led me in to looking at linger are being seen in qtwebview. I am seeing imaages not load intermittently on exttrreemelyy image heavy pages and Java script files being loaded vianrequire.js are failing onages with about two dozen js annd css files.  Since I still shouldn't be doing more than 50 requests in either case, I thought it wouldn't possibly anything to do with socket closing, but I think now I need to reexamine that.

**Comment by bel2125** [comment] 2016-04-02 06:36
Would you try the 100 and the 1000 image test in the test directory.
Would you also try the ajax test.
Please send your system info (call civetweb -I) - most likely it will not matter if the server runs on Windows or Linux - but if you have a chance to test it, then test two OS.
Retest with arora (the Qt WebKit demo), my old browser.exe (I only recently removed source and exe from the repo, maybe I can find a link somewhere), and a with FireFox (non Qt). I think the issue is not directly Qt related, but depends on the reload code.
When all the tests turn out the same result as (approximately?) 2012, the same fix might help - but its not a simple fix.

**Comment by bel2125** [comment] 2016-04-02 21:40
[Browser.zip](https://github.com/civetweb/civetweb/files/201048/Browser.zip)
[Browser_src.zip](https://github.com/civetweb/civetweb/files/201049/Browser_src.zip)
from https://code.google.com/r/bel2125-mongoose/Browser/Browser.cpp

**Comment by bel2125** [comment] 2016-09-11 18:44
Linger options have been changed with #355. See #237.

**Comment by bel2125** [comment] 2016-12-13 21:32
Finally there is an option linger\_timeout\_ms to define the linger behavior.
Please see the UserManual.md for details.

**Closed by bel2125** 2016-12-13 21:32 UTC
