### ISSUE TITLE
use_request_handler

### ISSUE THREAD

**Issue by pawel250** [civetweb/civetweb#255] opened 2016-02-08 12:46 UTC
Hi,
I discovered that getting some uri which are part of registered uri is impossible.

Example:
In my hosted directory I have file called test.jpg. 
I registered handler like below:
mg_set_request_handler(ctx,"/test", TestPageHandler,0);

When I try get URL localhost/test.jpg then server executes TestPageHandler instead of hosting test.jpg.
I solved problem temporary by comment out prefix matching in civetweb.c:5067:
/\* try for pattern match */
        if (match_prefix(tmp_rh->uri, tmp_rh->uri_len, uri) > 0) {
           //return tmp_rh->handler(conn, tmp_rh->cbdata);
        }

I think that this behaviour of match_prefix() was not intended. What do you think ?

Best Regards
Pawel

**Comment by bel2125** [comment] 2016-02-08 18:39
I think this is a duplicate of #179:

I don't like the way pattern matching is done in the moment, but changing this will certainly break compatibility.

You could solve the problem by calling `mg_send_file` from within the handler: 
https://github.com/civetweb/civetweb/blob/master/examples/embedded_c/embedded_c.c#L153

**Comment by bel2125** [comment] 2017-03-13 20:39
The documentation of patterns has been modified to minimize confusion. The rest of this issue is duplicate to #179 (other duplicates #255, #337, #376). I'm closing all duplicates except the original one (#179).

**Closed by bel2125** 2017-03-13 20:39 UTC
Labels: duplicate (see comment)
