### ISSUE TITLE
URI Handler for partial matches select first partial match instead of closest match

### ISSUE THREAD

**Issue by cdbishop** [civetweb/civetweb#179] opened 2015-07-27 10:48 UTC
In the embedded_c example there is a handle for /A and for /A/B.

If I run up the embedded_c sample and perform a request at the path /A/B/C, I would expect the request to be handled by /A/B, but in reality this request is handled by handler at /A.

The reason appears to be because the partial matches are performed in the order that the handlers where added, thus it partially matches /A successfully before checking /A/B. 

As a work around I, as the user can ensure that I add my handlers in order of most nested first e.g.

mg_set_request_handler("/A/B", ABHandler)
mg_set_request_handler("/A", AHandler)

But it would be great if I didn't have to worry about the addition order (as I have additions in different areas of my code)

I think a solution to this would be to have the handlers sorted by uri length (longest first). This could be done when one is set (in the mg_set_request_handler_type) by inserting the handler in the list such that they are ordered longest to shortest. That way Uri's with deep nesting would be checked first.

I can look into creating a pull request with this change if you agree with my expectation of finding the closest match in a partial search.

**Comment by bel2125** [comment] 2015-07-27 21:03
I know there are some problems in this area. My preferred solution is to completely rewrite all pattern matching and option parsing code, and to use more clever wildcards (just like in Lua pattern matching or simple regex). 
- /A/B should only match /A/B, not /A/B/C, not /A/BB, not anything else
- /A/B/* should match /A/B/C and /A/B/D/E but not /A/BB
- /A/B* should either be not allowed or match all above

But this will break compatibility.

The problem is, the API is not clean here.

I would also consider handlers like /customers/([%a]+)/orders/([%x]+)/items/([%x]+) as legitimate (see https://groups.google.com/forum/#!topic/civetweb/0CAukw3LWOs). It would be nice to allow this directly in the set_request_handler API. But this is something I won't do immediately.

I agree sorting by string length will make it better in the first place, but it still won't be perfect.

**Comment by PhilLab** [comment] 2016-02-20 13:25
Comment left by bel2125 at a now-closed duplicate of this issue (#260): 

> You could try a "$" at the end:

>     mg_set_request_handler(c, "**.js$", handler1 ... )
>     mg_set_request_handler(c, "**.json$",  handler2 ...)

>  This is not a general solution to all problems we have with pattern matching, but it should work in your case.

**Comment by bel2125** [comment] 2016-05-13 22:40
This will not be changed for version 1.8, but maybe later.

**Comment by bel2125** [comment] 2016-07-14 20:13
Probably, a new interface to match URIs according to https://tools.ietf.org/html/rfc6570 would be the best solution. It would have to have a list of variables found while matching the URI patterns.

**Comment by bel2125** [comment] 2017-03-13 20:44
The documentation of patterns has been modified to minimize confusion. I closed the duplicates #255, #260, #337, #376.

**Comment by bel2125** [comment] 2017-07-29 22:00
Source of this and many other issues is the pattern definition.
Closing this old issue, and tracking required interface changes with #499.

**Closed by bel2125** 2017-07-29 22:00 UTC
