### ISSUE TITLE
the listening_ports options in single value form does not work

### ISSUE THREAD

**Issue by trungnthut** [civetweb/civetweb#273] opened 2016-03-15 05:07 UTC
I don't know if this is your purpose or not. But when trying  with the single value like "8888", it just does not work, including the embedded_c demo.

After debugging, I found out that the ports value must be in the list form, so, using "8888,", it work.

I think this is inconvenience.

**Comment by bel2125** [comment] 2016-03-15 19:57
I just tried it again with the current code, and found no problems.
The unit test `test_mg_start_stop_http_server` [here](https://github.com/civetweb/civetweb/blob/master/test/public_server.c#L228) uses "8080". This test is executed for every pull request and every push of new code.

Where did you find this problem?

**Comment by bel2125** [comment] 2016-05-05 16:34
This problem did not occur in any of my tests.
Please provide some information how to reproduce this problem, and in particular what version you used.

Otherwise I will have to close this issue, since I do not know if there really is any problem, and if, I do not have any hint where to start looking.

**Comment by trungnthut** [comment] 2016-05-06 05:44
Hi, sorry almost forgot this issue. I could not reproduce it for now. May be I've made some mistake that time. Please close it!

Thanks!

**Comment by bel2125** [comment] 2016-05-06 18:38
Problem is not reproducible / maybe a mistake in the original test.
==> Closing this issue.

**Closed by bel2125** 2016-05-06 18:38 UTC
