### ISSUE TITLE
CivetWeb64 crashes on "Edit settings"

### ISSUE THREAD

**Issue by kainjow** [civetweb/civetweb#312] opened 2016-05-29 05:35 UTC
It appears the Windows 64-bit build is crashing. When I go to edit settings, it just closes.

The 32-bit one works without issue.

I'm on Windows 10.

**Comment by bel2125** [comment] 2016-05-29 08:06
The CivetWeb64.exe in the CivetWeb_Win32+64_V1.8.zip on SourceForge?
I tested exactly this executable on my Windows 10 64 bit PC.

I did build this executable with the VS2015 using the project- and solution-files in the repository.

Which build do you use precisely?

**Comment by kainjow** [comment] 2016-05-29 16:40
Yes, I used the 1.8 build on SourceForge.

**Comment by bel2125** [comment] 2016-05-29 18:09
I'm going to check it on another PC.

**Comment by bel2125** [comment] 2016-05-30 20:33
I could reproduce and solve the issue.
I replaced the 64 bit executable and gave it a label 1.8.1 -  this is exactly 1.8 plus 236411c3937b6b00fad1631c763242683602eb15. Probably this bug fix branch should be reflected in github as well - I need to check if there is a simple way to do this, or if it would be overkill.

**Comment by kainjow** [comment] 2016-05-30 20:41
You could branch from 1.8 commit, cherry pick in the fix, set version numbers to 1.8.1, and then tag it.

**Comment by bel2125** [comment] 2016-05-30 20:57
If only I would know how to do that ...
Probably I need to find and read some documentation first. There are some problems if I do a fork that replaces bel2125/civetweb, because currently bel2125/civetweb is a forward to civetweb/civetweb, and I don't want to overwrite this forward.

**Comment by kainjow** [comment] 2016-05-30 21:47
What git client do you use? If you use a GUI like SourceTree it's very easy. Just right click on the 1.8 commit, branch, then right click on the fix commit and cherry pick. Tag that branch as 1.8.1 then push that commit.

**Comment by bel2125** [comment] 2016-05-31 17:44
Plain git command shell. I have several different development machines, different Windows systems, Linux, sometimes I get patches by mail, ...
The only thing that works exactly the same on all systems is the git command line itself.
There I can also see what I'm doing, it's not hidden by the tool. I once had a tool that could handle several different source control systems. The source control systems used different names for similar concepts, the same names for different concepts, then there are the additional names defined by the GUI designers, and it was never really clear which of the 100 options in the tool works for what source control system.
I'm fine with the command line. Somewhere I do have a >100 pages PDF on how to use the git command line - I did not read it, but there was one chapter "if you only read one chapter, read this one", and that was pretty useful. I just can not remember where I found this PDF and where I stored it ... 
I'll find it sooner or later.

**Comment by kainjow** [comment] 2016-05-31 17:51
Ok, how about this:

    git branch v1.8.1 0165351
    git checkout v1.8.1
    git cherry-pick 236411c
    git tag v1.8.1
    git checkout master
    git branch -D v1.8.1 # optional
    git push --follow-tags

**Comment by bel2125** [comment] 2016-05-31 19:51
So this is not done in with the GitHub GUI. I was looking for a "Create branch" button around [here](https://github.com/civetweb/civetweb/branches) - just like there is a fork button. So I kind of expected a similar way to do branches).
I thought of
```
git branch v1.8_maintenance
```
than do one commit with the same changes as 236411c and a change of the version number in civetweb.h in the same commit with commit title v1.8.1 and a corresponding description text.

I think the branch can not be `v1.8.1`, because then the next fix would be a branch of the branch `v1.8.1.1` - if I would do a `v1.8.2` label it should not be inside the `v1.8.1` branch - the branch could be `v1.8.x` or `v1.8_maintenance`. 

On one hand, I want it to be an exception rather than the usual case to have a bug fix version while already working on the next release.
On the other hand, if it is done, it still must be done in an understandable and repeatable way.

**Comment by bel2125** [comment] 2016-06-10 17:51
I did not succeed in pushing the branch to github.
But this is nothing that needs to be tracked with this issue, so I will close it now since the original bug is fixed.

**Closed by bel2125** 2016-06-10 17:51 UTC
